// packages/ui-svelte/src/lib/components/TabsContent.svelte
<script lang="ts">
  /** Content panel shown when its matching tab is active. Requires a value prop. */
  import { getContext } from 'svelte'
  import { melt } from '@melt-ui/svelte'
  import { cn } from '../utils'
  interface Props { value: string; class?: string; children?: import('svelte').Snippet }
  const { value, class: cls = '', children }: Props = $props()
  const tabs = getContext<ReturnType<typeof import('@melt-ui/svelte').createTabs>>('paul-tabs')
</script>
<div use:melt={tabs.elements.content(value)} class={cn('mt-2 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring', cls)}>
  {@render children?.()}
</div>

// packages/ui-angular/src/lib/tabs/tabs-content.component.ts
import { Component, Input, HostBinding, Optional, ChangeDetectionStrategy } from '@angular/core'
import { CommonModule } from '@angular/common'
import { cn } from '../../lib/utils'
import { TabsComponent } from './tabs.component'

/** Content panel shown when its matching tab is active. */
@Component({
  selector: 'paul-tabs-content',
  standalone: true,
  imports: [CommonModule],
  template: `<ng-content *ngIf="active" />`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TabsContentComponent {
  @Input() value = ''
  @Input() class = ''

  constructor(@Optional() private tabs: TabsComponent) {}

  get active() { return this.tabs?.activeValue === this.value }

  @HostBinding('attr.role') role = 'tabpanel'
  @HostBinding('attr.data-state') get dataState() { return this.active ? 'active' : 'inactive' }
  @HostBinding('class') get hostClass() {
    return cn('mt-2 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring', this.class)
  }
}
