// packages/ui-svelte/src/lib/components/TabsTrigger.svelte
<script lang="ts">
  /** Tab button that activates its associated TabsContent panel. Requires a value prop. */
  import { getContext } from 'svelte'
  import { melt } from '@melt-ui/svelte'
  import { cn } from '../utils'
  interface Props { value: string; disabled?: boolean; class?: string; children?: import('svelte').Snippet }
  const { value, disabled = false, class: cls = '', children }: Props = $props()
  const tabs = getContext<ReturnType<typeof import('@melt-ui/svelte').createTabs>>('paul-tabs')
</script>
<button
  use:melt={tabs.elements.trigger(value)}
  {disabled}
  class={cn('inline-flex items-center justify-center whitespace-nowrap rounded-md px-3 py-1 text-sm font-medium ring-offset-background transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 data-[state=active]:bg-background data-[state=active]:text-foreground data-[state=active]:shadow', cls)}
>
  {@render children?.()}
</button>

// packages/ui-angular/src/lib/tabs/tabs-trigger.component.ts
import { Component, Input, HostBinding, HostListener, Optional, ChangeDetectionStrategy } from '@angular/core'
import { cn } from '../../lib/utils'
import { TabsComponent } from './tabs.component'

/** Tab button that activates its associated TabsContent panel. */
@Component({
  selector: 'paul-tabs-trigger',
  standalone: true,
  template: `<ng-content />`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TabsTriggerComponent {
  @Input() value = ''
  @Input() disabled = false
  @Input() class = ''

  constructor(@Optional() private tabs: TabsComponent) {}

  get active() { return this.tabs?.activeValue === this.value }

  @HostBinding('attr.role') role = 'tab'
  @HostBinding('attr.aria-selected') get ariaSelected() { return this.active }
  @HostBinding('attr.data-state') get dataState() { return this.active ? 'active' : 'inactive' }
  @HostBinding('class') get hostClass() {
    return cn(
      'inline-flex items-center justify-center whitespace-nowrap rounded-md px-3 py-1 text-sm font-medium ring-offset-background transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50',
      this.active ? 'bg-background text-foreground shadow' : '',
      this.class
    )
  }

  @HostListener('click')
  onClick() {
    if (!this.disabled) this.tabs?.select(this.value)
  }
}
