// packages/ui/src/components/resizable.tsx
import { GripVertical } from 'lucide-react'
import * as ResizablePrimitive from 'react-resizable-panels'
import { cn } from '@/lib/utils'

const ResizablePanelGroup = ({
  className,
  ...props
}: React.ComponentProps<typeof ResizablePrimitive.PanelGroup>) => (
  <ResizablePrimitive.PanelGroup
    className={cn(
      'flex h-full w-full data-[panel-group-direction=vertical]:flex-col',
      className
    )}
    {...props}
  />
)

const ResizablePanel = ResizablePrimitive.Panel

const ResizableHandle = ({
  withHandle,
  className,
  ...props
}: React.ComponentProps<typeof ResizablePrimitive.PanelResizeHandle> & {
  withHandle?: boolean
}) => (
  <ResizablePrimitive.PanelResizeHandle
    className={cn(
      'relative flex w-px items-center justify-center bg-border after:absolute after:inset-y-0 after:left-1/2 after:w-1 after:-translate-x-1/2 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring focus-visible:ring-offset-1 data-[panel-group-direction=vertical]:h-px data-[panel-group-direction=vertical]:w-full data-[panel-group-direction=vertical]:after:left-0 data-[panel-group-direction=vertical]:after:h-1 data-[panel-group-direction=vertical]:after:w-full data-[panel-group-direction=vertical]:after:-translate-y-1/2 data-[panel-group-direction=vertical]:after:translate-x-0 [&[data-panel-group-direction=vertical]>div]:rotate-90',
      className
    )}
    {...props}
  >
    {withHandle && (
      <div className="z-10 flex h-4 w-3 items-center justify-center rounded-sm border bg-border">
        <GripVertical className="h-2.5 w-2.5" />
      </div>
    )}
  </ResizablePrimitive.PanelResizeHandle>
)

export { ResizablePanelGroup, ResizablePanel, ResizableHandle }

// packages/ui-angular/src/lib/resizable/resizable.component.ts
import { Component, Input, ChangeDetectionStrategy } from '@angular/core'
import { CommonModule } from '@angular/common'

@Component({
  selector: 'paul-resizable-panel-group',
  standalone: true,
  imports: [CommonModule],
  template: `<div [class]="groupClass"><ng-content /></div>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ResizablePanelGroupComponent {
  @Input() direction: 'horizontal' | 'vertical' = 'horizontal'
  @Input() class = ''
  get groupClass() {
    return `flex h-full w-full data-[panel-group-direction=vertical]:flex-col ${this.direction === 'vertical' ? 'flex-col' : ''} ${this.class}`
  }
}

@Component({
  selector: 'paul-resizable-panel',
  standalone: true,
  template: `<div class="flex-1 overflow-auto"><ng-content /></div>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ResizablePanelComponent {}

@Component({
  selector: 'paul-resizable-handle',
  standalone: true,
  template: `<div class="relative flex w-px items-center justify-center bg-border after:absolute after:inset-y-0 after:left-1/2 after:w-1 after:-translate-x-1/2 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-1 data-[panel-group-direction=vertical]:h-px data-[panel-group-direction=vertical]:w-full"></div>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ResizableHandleComponent {}
