// packages/ui/src/components/table.tsx
import * as React from 'react'
import { cn } from '@/lib/utils'

/** Responsive `<table>` wrapper with overflow scroll. */
const Table = React.forwardRef<
  HTMLTableElement,
  React.HTMLAttributes<HTMLTableElement>
>(({ className, ...props }, ref) => (
  <div className="relative w-full overflow-auto">
    <table
      ref={ref}
      className={cn('w-full caption-bottom text-sm print:border-black', className)}
      {...props}
    />
  </div>
))
Table.displayName = 'Table'

/** `<thead>` section containing header rows. */
const TableHeader = React.forwardRef<
  HTMLTableSectionElement,
  React.HTMLAttributes<HTMLTableSectionElement>
>(({ className, ...props }, ref) => (
  <thead ref={ref} className={cn('[&_tr]:border-b print:[&_tr]:border-black', className)} {...props} />
))
TableHeader.displayName = 'TableHeader'

/** `<tbody>` section containing data rows. */
const TableBody = React.forwardRef<
  HTMLTableSectionElement,
  React.HTMLAttributes<HTMLTableSectionElement>
>(({ className, ...props }, ref) => (
  <tbody
    ref={ref}
    className={cn('[&_tr:last-child]:border-0 print:border-black', className)}
    {...props}
  />
))
TableBody.displayName = 'TableBody'

/** `<tfoot>` section for summary or totals rows. */
const TableFooter = React.forwardRef<
  HTMLTableSectionElement,
  React.HTMLAttributes<HTMLTableSectionElement>
>(({ className, ...props }, ref) => (
  <tfoot
    ref={ref}
    className={cn(
      'border-t bg-muted/50 font-medium [&>tr]:last:border-b-0 print:border-black',
      className
    )}
    {...props}
  />
))
TableFooter.displayName = 'TableFooter'

/** A `<tr>` row with hover and selected state styling. */
const TableRow = React.forwardRef<
  HTMLTableRowElement,
  React.HTMLAttributes<HTMLTableRowElement>
>(({ className, ...props }, ref) => (
  <tr
    ref={ref}
    className={cn(
      'border-b transition-colors hover:bg-muted/50 data-[state=selected]:bg-muted print:border-black',
      className
    )}
    {...props}
  />
))
TableRow.displayName = 'TableRow'

/** `<th>` header cell. */
const TableHead = React.forwardRef<
  HTMLTableCellElement,
  React.ThHTMLAttributes<HTMLTableCellElement>
>(({ className, ...props }, ref) => (
  <th
    ref={ref}
    className={cn(
      'h-10 px-2 text-start align-middle font-medium text-muted-foreground [&:has([role=checkbox])]:pe-0 [&>[role=checkbox]]:translate-y-[2px]',
      className
    )}
    {...props}
  />
))
TableHead.displayName = 'TableHead'

/** `<td>` data cell. */
const TableCell = React.forwardRef<
  HTMLTableCellElement,
  React.TdHTMLAttributes<HTMLTableCellElement>
>(({ className, ...props }, ref) => (
  <td
    ref={ref}
    className={cn(
      'p-2 align-middle [&:has([role=checkbox])]:pe-0 [&>[role=checkbox]]:translate-y-[2px]',
      className
    )}
    {...props}
  />
))
TableCell.displayName = 'TableCell'

/** `<caption>` element rendered below the table describing its contents. */
const TableCaption = React.forwardRef<
  HTMLTableCaptionElement,
  React.HTMLAttributes<HTMLTableCaptionElement>
>(({ className, ...props }, ref) => (
  <caption
    ref={ref}
    className={cn('mt-4 text-sm text-muted-foreground', className)}
    {...props}
  />
))
TableCaption.displayName = 'TableCaption'

export {
  Table,
  TableHeader,
  TableBody,
  TableFooter,
  TableHead,
  TableRow,
  TableCell,
  TableCaption,
}

// packages/ui-angular/src/lib/table/table.component.ts
import { Component, ChangeDetectionStrategy, HostBinding, Input } from '@angular/core'
import { cn } from '../../lib/utils'

@Component({ selector: 'paul-table', standalone: true, template: `<div class="relative w-full overflow-auto"><table class="w-full caption-bottom text-sm print:border-black"><ng-content /></table></div>`, changeDetection: ChangeDetectionStrategy.OnPush })
export class TableComponent {}

@Component({ selector: 'paul-table-header', standalone: true, template: `<thead class="[&_tr]:border-b print:[&_tr]:border-black"><ng-content /></thead>`, changeDetection: ChangeDetectionStrategy.OnPush })
export class TableHeaderComponent {}

@Component({ selector: 'paul-table-body', standalone: true, template: `<tbody class="[&_tr:last-child]:border-0 print:border-black"><ng-content /></tbody>`, changeDetection: ChangeDetectionStrategy.OnPush })
export class TableBodyComponent {}

@Component({ selector: 'paul-table-footer', standalone: true, template: `<tfoot class="border-t bg-muted/50 font-medium [&>tr]:last:border-b-0 print:border-black"><ng-content /></tfoot>`, changeDetection: ChangeDetectionStrategy.OnPush })
export class TableFooterComponent {}

@Component({ selector: 'paul-table-row', standalone: true, template: `<tr class="border-b transition-colors hover:bg-muted/50 data-[state=selected]:bg-muted print:border-black"><ng-content /></tr>`, changeDetection: ChangeDetectionStrategy.OnPush })
export class TableRowComponent {}

@Component({ selector: 'paul-table-head', standalone: true, template: `<th class="h-10 px-2 text-start align-middle font-medium text-muted-foreground [&:has([role=checkbox])]:pe-0 [&>[role=checkbox]]:translate-y-[2px]"><ng-content /></th>`, changeDetection: ChangeDetectionStrategy.OnPush })
export class TableHeadComponent {}

@Component({ selector: 'paul-table-cell', standalone: true, template: `<td class="p-2 align-middle [&:has([role=checkbox])]:pe-0 [&>[role=checkbox]]:translate-y-[2px]"><ng-content /></td>`, changeDetection: ChangeDetectionStrategy.OnPush })
export class TableCellComponent {}

@Component({ selector: 'paul-table-caption', standalone: true, template: `<caption class="mt-4 text-sm text-muted-foreground"><ng-content /></caption>`, changeDetection: ChangeDetectionStrategy.OnPush })
export class TableCaptionComponent {}
