// packages/ui-vue/src/components/separator.vue
<script setup lang="ts">
import { Separator as SeparatorRoot } from 'radix-vue'
import { cn } from '@/lib/utils'
/**
 * Separator — a visual or semantic divider between content sections.
 *
 * @example
 * ```vue
 * <Separator />
 * <Separator orientation="vertical" class="h-6" />
 * ```
 *
 * @accessibility Renders as `role="separator"` or `role="none"` based on the `decorative` prop.
 */
defineOptions({ name: 'Separator' })
const props = defineProps<{ orientation?: 'horizontal' | 'vertical'; decorative?: boolean; class?: string }>()
</script>
<template><SeparatorRoot v-bind="props" :class="cn('shrink-0 bg-border', props.orientation === 'vertical' ? 'h-full w-[1px]' : 'h-[1px] w-full', props.class)" /></template>

// packages/ui-angular/src/lib/separator/separator.component.ts
import { Component, Input, HostBinding, ChangeDetectionStrategy } from '@angular/core'
import { cn } from '../../lib/utils'

/**
 * Separator — a visual divider between content sections.
 *
 * @example
 * ```html
 * <paul-separator />
 * <paul-separator orientation="vertical" class="h-6" />
 * ```
 */
@Component({
  selector: 'paul-separator',
  standalone: true,
  template: ``,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SeparatorComponent {
  @Input() orientation: 'horizontal' | 'vertical' = 'horizontal'
  @Input() decorative = true
  @Input() class = ''
  @HostBinding('attr.role') get role() { return this.decorative ? 'none' : 'separator' }
  @HostBinding('attr.aria-orientation') get ariaOrientation() { return this.orientation }
  @HostBinding('class') get hostClass() {
    return cn(
      'shrink-0 bg-border',
      this.orientation === 'horizontal' ? 'h-[1px] w-full' : 'h-full w-[1px]',
      this.class
    )
  }
}
