// packages/ui-vue/src/components/input-group-text.vue
<script setup lang="ts">
import { cn } from '@/lib/utils'
/** Static text addon rendered inside an InputGroup as a prefix or suffix. */
defineOptions({ name: 'InputGroupText' })
const props = defineProps<{ class?: string }>()
</script>
<template><div :class="cn('flex items-center rounded-md border border-input bg-muted px-3 text-sm text-muted-foreground', props.class)"><slot /></div></template>

// packages/ui-angular/src/lib/input/input-group-text.component.ts
import { Component, Input, HostBinding, ChangeDetectionStrategy } from '@angular/core'
import { cn } from '../../lib/utils'

/** Static text addon rendered inside an InputGroup as a prefix or suffix. */
@Component({ selector: 'paul-input-group-text', standalone: true, template: `<ng-content />`, changeDetection: ChangeDetectionStrategy.OnPush })
export class InputGroupTextComponent {
  @Input() class = ''
  @HostBinding('class') get hostClass() {
    return cn('flex items-center rounded-md border border-input bg-muted px-3 text-sm text-muted-foreground', this.class)
  }
}
