// packages/ui-svelte/src/lib/components/InputGroup.svelte
<script lang="ts">
  /**
   * InputGroup — combines an input with prefix/suffix addons.
   *
   * @example
   * ```svelte
   * <InputGroup>
   *   <InputGroupText>https://</InputGroupText>
   *   <Input placeholder="example.com" />
   * </InputGroup>
   * ```
   */
  import { cn } from '../utils'
  interface Props { class?: string; children?: import('svelte').Snippet }
  const { class: cls = '', children }: Props = $props()
</script>
<div class={cn('flex [&>input]:rounded-none [&>input:first-child]:rounded-s-md [&>input:last-child]:rounded-e-md', cls)}>
  {@render children?.()}
</div>

// packages/ui-angular/src/lib/input/input-group.component.ts
import { Component, Input, HostBinding, ChangeDetectionStrategy } from '@angular/core'
import { cn } from '../../lib/utils'

/**
 * InputGroup — combines an input with prefix/suffix addons.
 *
 * @example
 * ```html
 * <paul-input-group>
 *   <paul-input-group-text>https://</paul-input-group-text>
 *   <input paul-input placeholder="example.com" />
 * </paul-input-group>
 * ```
 */
@Component({ selector: 'paul-input-group', standalone: true, template: `<ng-content />`, changeDetection: ChangeDetectionStrategy.OnPush })
export class InputGroupComponent {
  @Input() class = ''
  @HostBinding('class') get hostClass() {
    return cn('flex [&>input]:rounded-none [&>input:first-child]:rounded-s-md [&>input:last-child]:rounded-e-md', this.class)
  }
}
