// packages/ui-vue/src/components/alert-description.vue
<script setup lang="ts">
import { cn } from '@/lib/utils'
/** Supporting description text inside an Alert. */
defineOptions({ name: 'AlertDescription' })
const props = defineProps<{ class?: string }>()
</script>
<template><div :class="cn('text-sm [&_p]:leading-relaxed', props.class)"><slot /></div></template>

// packages/ui-angular/src/lib/alert/alert-description.component.ts
import { Component, Input, HostBinding, ChangeDetectionStrategy } from '@angular/core'
import { cn } from '../../lib/utils'

/** Supporting description text inside an Alert. */
@Component({
  selector: 'paul-alert-description',
  standalone: true,
  template: `<ng-content />`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AlertDescriptionComponent {
  @Input() class = ''
  @HostBinding('class') get hostClass() {
    return cn('text-sm [&_p]:leading-relaxed', this.class)
  }
}
