// packages/ui-vue/src/components/empty.vue
<script setup lang="ts">
import { cn } from '@/lib/utils'
/**
 * Empty — empty state placeholder with optional icon, title, description, and action.
 *
 * @example
 * ```vue
 * <Empty title="No results" description="Try adjusting your filters.">
 *   <template #icon><SearchX class="h-12 w-12 text-muted-foreground" /></template>
 *   <template #action><Button>Clear filters</Button></template>
 * </Empty>
 * ```
 */
defineOptions({ name: 'Empty' })
const props = defineProps<{ title?: string; description?: string; class?: string }>()
</script>
<template>
  <div :class="cn('flex flex-col items-center justify-center text-center p-8', props.class)">
    <slot name="icon" />
    <h3 v-if="props.title" class="mt-4 text-lg font-semibold">{{ props.title }}</h3>
    <p v-if="props.description" class="mt-2 text-sm text-muted-foreground">{{ props.description }}</p>
    <div v-if="$slots.action" class="mt-4"><slot name="action" /></div>
  </div>
</template>

// packages/ui/src/components/empty.tsx
import * as React from 'react'
import { cn } from '@/lib/utils'

interface EmptyProps extends React.HTMLAttributes<HTMLDivElement> {
  /** Icon element displayed at the top of the empty state. */
  icon?: React.ReactNode
  /** Primary heading text. */
  title?: string
  /** Supporting description text rendered below the title. */
  description?: string
  /** Optional action element (e.g. a Button) rendered below the description. */
  action?: React.ReactNode
}

/**
 * Empty — a centred empty-state layout with optional icon, title, description, and action.
 *
 * @example
 * ```tsx
 * <Empty
 *   icon={<InboxIcon className="h-8 w-8 text-muted-foreground" />}
 *   title="No results"
 *   description="Try adjusting your filters."
 *   action={<Button>Clear filters</Button>}
 * />
 * ```
 */
const Empty = React.forwardRef<HTMLDivElement, EmptyProps>(
  ({ className, icon, title, description, action, ...props }, ref) => {
    return (
      <div
        ref={ref}
        className={cn(
          'flex flex-col items-center justify-center text-center p-8',
          className
        )}
        {...props}
      >
        {icon && (
          <div className="flex h-20 w-20 items-center justify-center rounded-full bg-muted mb-4">
            {icon}
          </div>
        )}
        {title && (
          <h3 className="text-lg font-semibold text-foreground mb-2">{title}</h3>
        )}
        {description && (
          <p className="text-sm text-muted-foreground max-w-xs mb-4">
            {description}
          </p>
        )}
        {action && <div>{action}</div>}
      </div>
    )
  }
)
Empty.displayName = 'Empty'

export { Empty }
