// packages/ui-vue/src/components/spinner.vue
<script setup lang="ts">
import { type VariantProps, cva } from 'class-variance-authority'
import { Loader2 } from 'lucide-vue-next'
import { cn } from '@/lib/utils'
const spinnerVariants = cva('animate-spin text-muted-foreground', {
  variants: { size: { sm: 'h-4 w-4', default: 'h-6 w-6', lg: 'h-8 w-8', xl: 'h-12 w-12' } },
  defaultVariants: { size: 'default' },
})
interface SpinnerProps {
  size?: 'sm' | 'default' | 'lg' | 'xl'
  class?: string
}
/**
 * Spinner — animated loading indicator.
 *
 * @example
 * ```vue
 * <Spinner />
 * <Spinner size="lg" />
 * ```
 *
 * @accessibility Wrap with `<span role="status" aria-label="Loading">` if conveying load state to screen readers.
 */
defineOptions({ name: 'Spinner' })
const props = defineProps<SpinnerProps>()
</script>
<template><div :class="cn('flex items-center justify-center', props.class)"><Loader2 :class="spinnerVariants({ size: props.size })" /></div></template>

// packages/ui/src/components/spinner.tsx
import * as React from 'react'
import { cva, type VariantProps } from 'class-variance-authority'
import { cn } from '@/lib/utils'
import { Loader2 } from 'lucide-react'

const spinnerVariants = cva('animate-spin text-primary', {
  variants: {
    size: {
      default: 'h-4 w-4',
      sm: 'h-2 w-2',
      lg: 'h-6 w-6',
      xl: 'h-8 w-8',
    },
  },
  defaultVariants: {
    size: 'default',
  },
})

interface SpinnerProps
  extends React.HTMLAttributes<HTMLDivElement>,
    VariantProps<typeof spinnerVariants> {
  /** Size of the spinner icon. @default 'default' */
  size?: 'sm' | 'default' | 'lg' | 'xl'
  /** When true, renders the child element as the root via Radix Slot. */
  asChild?: boolean
}

/**
 * Spinner — an animated loading indicator using a `Loader2` icon.
 *
 * @example
 * ```tsx
 * <Spinner />
 * <Spinner size="lg" />
 * ```
 *
 * @accessibility Wrap with `role="status"` and a visually-hidden label when used
 * as a standalone loading state: `<span role="status"><Spinner /><span className="sr-only">Loading…</span></span>`
 */
const Spinner = React.forwardRef<HTMLDivElement, SpinnerProps>(
  ({ className, size, ...props }, ref) => {
    return (
      <div ref={ref} className={cn(spinnerVariants({ size }), className)} {...props}>
        <Loader2 className="h-full w-full" />
      </div>
    )
  }
)
Spinner.displayName = 'Spinner'

export { Spinner, spinnerVariants }
