// packages/ui-svelte/src/lib/components/Progress.svelte
<script lang="ts">
  // @ts-nocheck
  /**
   * Progress — linear progress bar backed by Melt UI.
   *
   * @example
   * ```svelte
   * <Progress value={75} />
   * ```
   *
   * @accessibility Sets role="progressbar" and aria-valuenow automatically.
   */
  import { createProgress, melt } from '@melt-ui/svelte'
  import { cn } from '../utils'

  interface Props { value?: number; max?: number; class?: string }
  const { value = 0, max = 100, class: cls = '' }: Props = $props()

  const { elements: { root }, options } = createProgress({ defaultValue: 0, max: 100 })
  $effect(() => { options.max.set(max) })
</script>
<div use:melt={root} class={cn('relative h-2 w-full overflow-hidden rounded-full bg-primary/20', cls)}>
  <div class="h-full bg-primary transition-all" style="width: {(value / max) * 100}%"></div>
</div>

// packages/ui-angular/src/lib/progress/progress.component.ts
import { Component, Input, ChangeDetectionStrategy } from '@angular/core'
import { CommonModule } from '@angular/common'
import { cn } from '../../lib/utils'

/**
 * Progress — linear progress bar.
 *
 * @example
 * ```html
 * <paul-progress [value]="75" />
 * ```
 */
@Component({
  selector: 'paul-progress',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div
      role="progressbar"
      [attr.aria-valuenow]="value"
      [attr.aria-valuemin]="0"
      [attr.aria-valuemax]="max"
      [class]="trackClass"
    >
      <div [class]="fillClass" [style.width.%]="pct"></div>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ProgressComponent {
  @Input() value = 0
  @Input() max = 100
  @Input() class = ''
  get pct() { return Math.min(100, Math.max(0, (this.value / this.max) * 100)) }
  get trackClass() { return cn('relative h-2 w-full overflow-hidden rounded-full bg-primary/20', this.class) }
  get fillClass() { return 'h-full bg-primary transition-all' }
}
