// packages/ui-vue/src/components/switch.vue
<script setup lang="ts">
import { SwitchRoot, SwitchThumb, type SwitchRootProps } from 'radix-vue'
import { cn } from '@/lib/utils'
/**
 * Switch — toggle switch for binary on/off settings.
 *
 * @example
 * ```vue
 * <Switch id="airplane" v-model:checked="airplaneMode" />
 * <Label for="airplane">Airplane Mode</Label>
 * ```
 *
 * @accessibility Backed by Radix Vue SwitchRoot. Reports `role="switch"` with `aria-checked`.
 * Track is 24×44px (WCAG 2.5.8 AA). For strict AAA (44×44px),
 * wrap with padding or use a larger container that extends the clickable region.
 */
defineOptions({ name: 'Switch' })
const props = defineProps<{ class?: string }>()
</script>
<template>
  <SwitchRoot v-bind="props" :class="cn('peer inline-flex h-6 w-11 shrink-0 cursor-pointer items-center rounded-full border-2 border-transparent shadow-sm transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:bg-primary data-[state=unchecked]:bg-input', props.class)">
    <SwitchThumb class="pointer-events-none block h-5 w-5 rounded-full bg-background shadow-lg ring-0 transition-transform data-[state=checked]:translate-x-6 data-[state=unchecked]:translate-x-0" />
  </SwitchRoot>
</template>

// packages/ui-angular/src/lib/switch/switch.component.ts
import { Component, Input, Output, EventEmitter, HostBinding, forwardRef, ChangeDetectionStrategy } from '@angular/core'
import { CommonModule } from '@angular/common'
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms'
import { cn } from '../../lib/utils'

/**
 * Switch — toggle switch for binary on/off settings.
 *
 * @example
 * ```html
 * <paul-switch id="airplane" [(ngModel)]="airplaneMode" />
 * <label paul-label for="airplane">Airplane Mode</label>
 * ```
 *
 * @accessibility Track is 24×44px (WCAG 2.5.8 AA). For strict AAA (44×44px),
 *   wrap with padding or use a larger container that extends the clickable region.
 */
@Component({
  selector: 'paul-switch',
  standalone: true,
  imports: [CommonModule],
  template: `
    <button
      type="button"
      role="switch"
      [attr.aria-checked]="checked"
      [attr.data-state]="checked ? 'checked' : 'unchecked'"
      [disabled]="disabled || null"
      [class]="trackClass"
      (click)="toggle()"
    >
      <span [class]="thumbClass"></span>
    </button>
  `,
  providers: [{ provide: NG_VALUE_ACCESSOR, useExisting: forwardRef(() => SwitchComponent), multi: true }],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SwitchComponent implements ControlValueAccessor {
  @Input() checked = false
  @Input() disabled = false
  @Input() class = ''
  @Output() checkedChange = new EventEmitter<boolean>()

  private onChange: (v: boolean) => void = () => {}
  private onTouched: () => void = () => {}

  get trackClass() {
    return cn(
      'peer inline-flex h-6 w-11 shrink-0 cursor-pointer items-center rounded-full border-2 border-transparent shadow-sm transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:ring-offset-background disabled:cursor-not-allowed disabled:opacity-50',
      this.checked ? 'bg-primary' : 'bg-input',
      this.class
    )
  }
  get thumbClass() {
    return cn(
      'pointer-events-none block h-5 w-5 rounded-full bg-background shadow-lg ring-0 transition-transform',
      this.checked ? 'translate-x-6' : 'translate-x-0'
    )
  }

  toggle() {
    if (this.disabled) return
    this.checked = !this.checked
    this.onChange(this.checked)
    this.onTouched()
    this.checkedChange.emit(this.checked)
  }

  writeValue(val: boolean) { this.checked = val }
  registerOnChange(fn: (v: boolean) => void) { this.onChange = fn }
  registerOnTouched(fn: () => void) { this.onTouched = fn }
  setDisabledState(d: boolean) { this.disabled = d }
}
