// packages/ui-svelte/src/lib/components/AccordionItem.svelte
<script lang="ts">
  /** A single accordion section. Requires a unique `value` prop. */
  import { getContext } from 'svelte'
  import { melt } from '@melt-ui/svelte'

  interface Props {
    value: string
    class?: string
    children?: import('svelte').Snippet
  }
  const { value, class: cls = '', children }: Props = $props()
  const accordion = getContext<any>('paul-accordion')
</script>
<div use:melt={accordion.elements.item(value)} class={['border-b', cls].filter(Boolean).join(' ')}>
  {@render children?.()}
</div>

// packages/ui-vue/src/components/accordion-item.vue
<script setup lang="ts">
import { AccordionItem, type AccordionItemProps } from 'radix-vue'
import { cn } from '@/lib/utils'

/** A single accordion section. Requires a unique `value` prop. */
defineOptions({ name: 'AccordionItem' })
const props = defineProps<{ class?: string }>()
</script>

<template>
  <AccordionItem v-bind="props" :class="cn('border-b', props.class)">
    <slot />
  </AccordionItem>
</template>
