// packages/ui-svelte/src/lib/components/AccordionContent.svelte
<script lang="ts">
  /** Collapsible content panel rendered below AccordionTrigger. */
  import { getContext } from 'svelte'
  import { melt } from '@melt-ui/svelte'
  import { cn } from '../utils'

  interface Props {
    value: string
    class?: string
    children?: import('svelte').Snippet
  }
  const { value, class: cls = '', children }: Props = $props()
  const accordion = getContext<any>('paul-accordion')
</script>
<div use:melt={accordion.elements.content(value)} class={cn('overflow-hidden text-sm data-[state=closed]:animate-accordion-up data-[state=open]:animate-accordion-down', cls)}>
  <div class="pb-4 pt-0">{@render children?.()}</div>
</div>

// packages/ui-vue/src/components/accordion-content.vue
<script setup lang="ts">
import { AccordionContent, type AccordionContentProps } from 'radix-vue'
import { cn } from '@/lib/utils'

/** Collapsible content panel rendered below AccordionTrigger. Animates open/closed via data attributes. */
defineOptions({ name: 'AccordionContent' })
const props = defineProps<{ class?: string }>()
</script>

<template>
  <AccordionContent
    v-bind="props"
    class="overflow-hidden text-sm data-[state=closed]:animate-accordion-up data-[state=open]:animate-accordion-down"
  >
    <div :class="cn('pb-4 pt-0', props.class)">
      <slot />
    </div>
  </AccordionContent>
</template>
