// packages/ui-angular/src/lib/alert/alert.component.ts
import { Component, Input, HostBinding, ChangeDetectionStrategy } from '@angular/core'
import { cva } from 'class-variance-authority'
import { cn } from '../../lib/utils'

/**
 * CVA variant config for AlertComponent.
 *
 * @variant default     - Neutral background with default foreground text.
 * @variant destructive - Red border and text for error or danger states.
 */
const alertVariants = cva(
  'relative w-full rounded-lg border px-4 py-3 text-sm [&>svg+div]:translate-y-[-3px] [&>svg]:absolute [&>svg]:start-4 [&>svg]:top-4 [&>svg]:text-foreground [&>svg~*]:ps-7 print:shadow-none print:border-black print:text-black',
  {
    variants: {
      variant: {
        default: 'bg-background text-foreground',
        destructive: 'border-destructive/50 text-destructive-text dark:border-destructive [&>svg]:text-destructive-text',
      },
    },
    defaultVariants: { variant: 'default' },
  }
)

/**
 * Alert — contextual feedback banner for info, warning, success, or error states.
 *
 * @example
 * ```html
 * <paul-alert>
 *   <paul-alert-title>Heads up</paul-alert-title>
 *   <paul-alert-description>You can add components to your app.</paul-alert-description>
 * </paul-alert>
 * <paul-alert variant="destructive">
 *   <paul-alert-title>Error</paul-alert-title>
 *   <paul-alert-description>Your session has expired.</paul-alert-description>
 * </paul-alert>
 * ```
 *
 * @accessibility Uses `role="alert"` so screen readers announce changes immediately.
 */
@Component({
  selector: 'paul-alert',
  standalone: true,
  template: `<ng-content />`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AlertComponent {
  @Input() variant: 'default' | 'destructive' = 'default'
  @Input() class = ''
  @HostBinding('attr.role') role = 'alert'
  @HostBinding('class') get hostClass() {
    return cn(alertVariants({ variant: this.variant }), this.class)
  }
}

// packages/ui-vue/src/components/alert.vue
<script setup lang="ts">
import { type VariantProps, cva } from 'class-variance-authority'
import { cn } from '@/lib/utils'
import AlertTitle from './alert-title.vue'
import AlertDescription from './alert-description.vue'

const alertVariants = cva(
  'relative w-full rounded-lg border px-4 py-3 text-sm [&>svg+div]:translate-y-[-3px] [&>svg]:absolute [&>svg]:start-4 [&>svg]:top-4 [&>svg]:text-foreground [&>svg~*]:ps-7 print:shadow-none print:border-black print:text-black',
  {
    variants: {
      variant: {
        default: 'bg-background text-foreground',
        destructive: 'border-destructive/50 text-destructive-text dark:border-destructive [&>svg]:text-destructive-text',
      },
    },
    defaultVariants: { variant: 'default' },
  }
)

interface AlertProps {
  as?: string
  variant?: 'default' | 'destructive'
  class?: string
  title?: string
  description?: string
}
/**
 * Alert — contextual feedback banner for info, warning, success, or error states.
 *
 * @example
 * ```vue
 * <Alert>
 *   <AlertTitle>Heads up</AlertTitle>
 *   <AlertDescription>You can add components to your app.</AlertDescription>
 * </Alert>
 * <Alert variant="destructive">
 *   <AlertTitle>Error</AlertTitle>
 *   <AlertDescription>Your session has expired.</AlertDescription>
 * </Alert>
 * ```
 * @example
 * ```vue
 * <Alert title="Heads up" description="You can add components to your app." />
 * ```
 *
 * @accessibility Uses `role="alert"` so screen readers announce changes immediately.
 */
defineOptions({ name: 'Alert' })
const props = defineProps<AlertProps>()
const tag = props.as || 'div'
</script>

<template>
  <component :is="tag" role="alert" :class="cn(alertVariants({ variant: props.variant }), props.class)">
    <slot>
      <AlertTitle v-if="props.title">{{ props.title }}</AlertTitle>
      <AlertDescription v-if="props.description">{{ props.description }}</AlertDescription>
    </slot>
  </component>
</template>
