// packages/ui-react/src/components/alert.tsx
import * as React from 'react'
import { cva, type VariantProps } from 'class-variance-authority'
import { cn } from '@/lib/utils'

const alertVariants = cva(
  'relative w-full rounded-lg border px-4 py-3 text-sm [&>svg+div]:translate-y-[-3px] [&>svg]:absolute [&>svg]:start-4 [&>svg]:top-4 [&>svg]:text-foreground [&>svg~*]:ps-7 print:shadow-none print:border-black print:text-black',
  {
    variants: {
      variant: {
        default: 'bg-background text-foreground',
        destructive:
          'border-destructive/50 text-destructive-text dark:border-destructive [&>svg]:text-destructive-text',
      },
    },
    defaultVariants: {
      variant: 'default',
    },
  }
)

/**
 * Alert container with a `role="alert"` for accessibility.
 * @prop variant - Visual style: 'default' | 'destructive'. @default 'default'
 */
const Alert = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement> & VariantProps<typeof alertVariants>
>(({ className, variant, ...props }, ref) => (
  <div
    ref={ref}
    role="alert"
    className={cn(alertVariants({ variant }), className)}
    {...props}
  />
))
Alert.displayName = 'Alert'

/** Heading element rendered inside an `Alert`. */
const AlertTitle = React.forwardRef<
  HTMLParagraphElement,
  React.HTMLAttributes<HTMLHeadingElement>
>(({ className, ...props }, ref) => (
  <h5
    ref={ref}
    className={cn('mb-1 font-medium leading-none tracking-tight', className)}
    {...props}
  />
))
AlertTitle.displayName = 'AlertTitle'

/** Supporting description text rendered inside an `Alert`. */
const AlertDescription = React.forwardRef<
  HTMLParagraphElement,
  React.HTMLAttributes<HTMLParagraphElement>
>(({ className, ...props }, ref) => (
  <div
    ref={ref}
    className={cn('text-sm [&_p]:leading-relaxed', className)}
    {...props}
  />
))
AlertDescription.displayName = 'AlertDescription'

export { Alert, AlertTitle, AlertDescription }

// packages/ui-vue/src/components/alert.vue
<script setup lang="ts">
import { type VariantProps, cva } from 'class-variance-authority'
import { cn } from '@/lib/utils'
import AlertTitle from './alert-title.vue'
import AlertDescription from './alert-description.vue'

const alertVariants = cva(
  'relative w-full rounded-lg border px-4 py-3 text-sm [&>svg+div]:translate-y-[-3px] [&>svg]:absolute [&>svg]:start-4 [&>svg]:top-4 [&>svg]:text-foreground [&>svg~*]:ps-7 print:shadow-none print:border-black print:text-black',
  {
    variants: {
      variant: {
        default: 'bg-background text-foreground',
        destructive: 'border-destructive/50 text-destructive-text dark:border-destructive [&>svg]:text-destructive-text',
      },
    },
    defaultVariants: { variant: 'default' },
  }
)

interface AlertProps {
  as?: string
  variant?: 'default' | 'destructive'
  class?: string
  title?: string
  description?: string
}
/**
 * Alert — contextual feedback banner for info, warning, success, or error states.
 *
 * @example
 * ```vue
 * <Alert>
 *   <AlertTitle>Heads up</AlertTitle>
 *   <AlertDescription>You can add components to your app.</AlertDescription>
 * </Alert>
 * <Alert variant="destructive">
 *   <AlertTitle>Error</AlertTitle>
 *   <AlertDescription>Your session has expired.</AlertDescription>
 * </Alert>
 * ```
 * @example
 * ```vue
 * <Alert title="Heads up" description="You can add components to your app." />
 * ```
 *
 * @accessibility Uses `role="alert"` so screen readers announce changes immediately.
 */
defineOptions({ name: 'Alert' })
const props = defineProps<AlertProps>()
const tag = props.as || 'div'
</script>

<template>
  <component :is="tag" role="alert" :class="cn(alertVariants({ variant: props.variant }), props.class)">
    <slot>
      <AlertTitle v-if="props.title">{{ props.title }}</AlertTitle>
      <AlertDescription v-if="props.description">{{ props.description }}</AlertDescription>
    </slot>
  </component>
</template>
