// packages/ui-angular/src/lib/alert/alert-title.component.ts
import { Component, Input, HostBinding, ChangeDetectionStrategy } from '@angular/core'
import { cn } from '../../lib/utils'

/** Primary heading inside an Alert. */
@Component({
  selector: 'paul-alert-title',
  standalone: true,
  template: `<ng-content />`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AlertTitleComponent {
  @Input() class = ''
  @HostBinding('class') get hostClass() {
    return cn('mb-1 font-medium leading-none tracking-tight', this.class)
  }
}

// packages/ui-vue/src/components/alert-title.vue
<script setup lang="ts">
import { cn } from '@/lib/utils'
/** Primary heading inside an Alert. */
defineOptions({ name: 'AlertTitle' })
const props = defineProps<{ class?: string }>()
</script>
<template><h5 :class="cn('mb-1 font-medium leading-none tracking-tight', props.class)"><slot /></h5></template>
