// packages/ui-svelte/src/lib/components/Avatar.svelte
<script lang="ts">
  /**
   * Avatar — container for user avatars.
   *
   * @example
   * ```svelte
   * <Avatar>
   *   <AvatarImage src="https://github.com/shadcn.png" alt="@shadcn" />
   *   <AvatarFallback>SC</AvatarFallback>
   * </Avatar>
   * ```
   */
  import { cn } from '../utils'
  interface Props { class?: string; children?: import('svelte').Snippet }
  const { class: cls = '', children }: Props = $props()
</script>
<span class={cn('relative flex h-10 w-10 shrink-0 overflow-hidden rounded-full', cls)}>
  {@render children?.()}
</span>

// packages/ui-vue/src/components/avatar.vue
<script setup lang="ts">
import { AvatarRoot, AvatarImage, AvatarFallback, type AvatarRootProps } from 'radix-vue'
import { cn } from '@/lib/utils'

/**
 * Avatar — root container for user avatars. Combine with AvatarImage and AvatarFallback.
 *
 * @example
 * ```vue
 * <Avatar>
 *   <AvatarImage src="https://github.com/shadcn.png" alt="@shadcn" />
 *   <AvatarFallback>SC</AvatarFallback>
 * </Avatar>
 * ```
 *
 * @accessibility Always provide an `alt` on AvatarImage, or ensure AvatarFallback text is meaningful.
 */
defineOptions({ name: 'Avatar' })
const props = defineProps<{ class?: string }>()
</script>

<template>
  <AvatarRoot v-bind="props" :class="cn('relative flex h-10 w-10 shrink-0 overflow-hidden rounded-full', props.class)">
    <slot />
  </AvatarRoot>
</template>
