// packages/ui-svelte/src/lib/components/AvatarImage.svelte
<script lang="ts">
  /** Image inside an Avatar. Shows the fallback if the image fails to load. */
  import { cn } from '../utils'
  interface Props { src: string; alt: string; class?: string }
  const { src, alt, class: cls = '' }: Props = $props()
  let error = $state(false)
</script>
{#if !error}
  <img {src} {alt} class={cn('aspect-square h-full w-full', cls)} onerror={() => (error = true)} />
{/if}

// packages/ui-vue/src/components/avatar-image.vue
<script setup lang="ts">
import { AvatarImage, type AvatarImageProps } from 'radix-vue'
import { cn } from '@/lib/utils'

/** Image element inside an Avatar. Shows the fallback if the image fails to load. */
defineOptions({ name: 'AvatarImage' })
const props = defineProps<{ src: string; class?: string }>()
</script>

<template>
  <AvatarImage v-bind="props" :class="cn('aspect-square h-full w-full', props.class)" />
</template>
