// packages/ui-angular/src/lib/button/button-group.component.ts
import { Component, Input, HostBinding, ChangeDetectionStrategy } from '@angular/core'
import { cn } from '../../lib/utils'

/**
 * ButtonGroup — renders a horizontal group of buttons with merged borders.
 *
 * @example
 * ```html
 * <paul-button-group>
 *   <button paul-button variant="outline">Left</button>
 *   <button paul-button variant="outline">Middle</button>
 *   <button paul-button variant="outline">Right</button>
 * </paul-button-group>
 * ```
 */
@Component({
  selector: 'paul-button-group',
  standalone: true,
  template: `<ng-content />`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ButtonGroupComponent {
  @Input() class = ''
  @HostBinding('class') get hostClass() {
    return cn('flex [&>*:not(:first-child)]:-ml-px [&>*:not(:first-child)]:rounded-l-none [&>*:not(:last-child)]:rounded-r-none', this.class)
  }
}

// packages/ui-vue/src/components/button-group.vue
<script setup lang="ts">
import { cn } from '@/lib/utils'
/**
 * ButtonGroup — renders a horizontal group of buttons with no gap and merged borders.
 *
 * @example
 * ```vue
 * <ButtonGroup>
 *   <Button variant="outline">Left</Button>
 *   <Button variant="outline">Middle</Button>
 *   <Button variant="outline">Right</Button>
 * </ButtonGroup>
 * ```
 */
defineOptions({ name: 'ButtonGroup' })
const props = defineProps<{ class?: string }>()
</script>

<template>
  <div :class="cn('flex [&>*:not(:first-child)]:-ms-px [&>*:not(:first-child)]:rounded-s-none [&>*:not(:last-child)]:rounded-e-none', props.class)">
    <slot />
  </div>
</template>
