// packages/ui-react/src/components/button-group.tsx
import * as React from 'react'
import { cva, type VariantProps } from 'class-variance-authority'
import { cn } from '@/lib/utils'

const buttonGroupVariants = cva(
  'inline-flex items-center justify-center gap-0 [&>*:not(:first-child)]:rounded-l-none [&>*:not(:last-child)]:rounded-r-none [&>*:not(:last-child)]:border-r-0'
)

interface ButtonGroupProps
  extends React.HTMLAttributes<HTMLDivElement>,
    VariantProps<typeof buttonGroupVariants> {
  /** Button elements to group together. Adjacent borders are merged via CSS. */
  children?: React.ReactNode
}

/**
 * ButtonGroup — renders a row of buttons with adjacent borders merged into a single unit.
 *
 * @example
 * ```tsx
 * <ButtonGroup>
 *   <Button variant="outline">Left</Button>
 *   <Button variant="outline">Center</Button>
 *   <Button variant="outline">Right</Button>
 * </ButtonGroup>
 * ```
 */
const ButtonGroup = React.forwardRef<HTMLDivElement, ButtonGroupProps>(
  ({ className, ...props }, ref) => {
    return (
      <div
        ref={ref}
        className={cn(buttonGroupVariants(), className)}
        {...props}
      />
    )
  }
)
ButtonGroup.displayName = 'ButtonGroup'

export { ButtonGroup, buttonGroupVariants }

// packages/ui-vue/src/components/button-group.vue
<script setup lang="ts">
import { cn } from '@/lib/utils'
/**
 * ButtonGroup — renders a horizontal group of buttons with no gap and merged borders.
 *
 * @example
 * ```vue
 * <ButtonGroup>
 *   <Button variant="outline">Left</Button>
 *   <Button variant="outline">Middle</Button>
 *   <Button variant="outline">Right</Button>
 * </ButtonGroup>
 * ```
 */
defineOptions({ name: 'ButtonGroup' })
const props = defineProps<{ class?: string }>()
</script>

<template>
  <div :class="cn('flex [&>*:not(:first-child)]:-ms-px [&>*:not(:first-child)]:rounded-s-none [&>*:not(:last-child)]:rounded-e-none', props.class)">
    <slot />
  </div>
</template>
