// packages/ui-svelte/src/lib/components/Calendar.svelte
<script lang="ts">
  let { selected = $bindable<Date | undefined>(undefined), class: className = '', locale, ...props } = $props<{ selected?: Date; class?: string; locale?: string; [key: string]: unknown }>()

  let today = new Date()
  let viewing = $state(new Date(today.getFullYear(), today.getMonth(), 1))

  function resolveLocale(): string {
    return locale ?? (typeof navigator !== 'undefined' ? navigator.language : 'en-US')
  }

  function getWeekStart(loc: string): number {
    try {
      const info = (new Intl.Locale(loc) as unknown as { weekInfo?: { firstDay: number } }).weekInfo
      if (info) return info.firstDay
    } catch { /* ignore */ }
    const table: Record<string, number> = { de: 1, fr: 1, it: 1, es: 1, ar: 0, en: 0 }
    return table[loc.split('-')[0]] ?? 0
  }

  let weekStart = $derived(getWeekStart(resolveLocale()))

  let dayNames = $derived(() => {
    const loc = resolveLocale()
    const fmt = new Intl.DateTimeFormat(loc, { weekday: 'short' })
    const ws = weekStart
    const sunBased = Array.from({ length: 7 }, (_, i) => fmt.format(new Date(2024, 0, 7 + i)))
    return [...sunBased.slice(ws), ...sunBased.slice(0, ws)]
  })()

  let daysInMonth = $derived(new Date(viewing.getFullYear(), viewing.getMonth() + 1, 0).getDate())
  let firstDow = $derived(new Date(viewing.getFullYear(), viewing.getMonth(), 1).getDay())
  let leadingBlanks = $derived(((firstDow - weekStart + 7) % 7))
  let monthLabel = $derived(
    new Intl.DateTimeFormat(resolveLocale(), { month: 'long', year: 'numeric' })
      .format(new Date(viewing.getFullYear(), viewing.getMonth(), 1))
  )

  function prevMonth() {
    viewing = new Date(viewing.getFullYear(), viewing.getMonth() - 1, 1)
  }
  function nextMonth() {
    viewing = new Date(viewing.getFullYear(), viewing.getMonth() + 1, 1)
  }
  function selectDay(d: number) {
    selected = new Date(viewing.getFullYear(), viewing.getMonth(), d)
  }
  function isSame(d: number) {
    return selected && selected.getFullYear() === viewing.getFullYear() && selected.getMonth() === viewing.getMonth() && selected.getDate() === d
  }
  function isToday(d: number) {
    return today.getFullYear() === viewing.getFullYear() && today.getMonth() === viewing.getMonth() && today.getDate() === d
  }
</script>

<div class={['p-3', className].join(' ')} {...props}>
  <div class="flex items-center justify-between mb-2">
    <button onclick={prevMonth} aria-label="Go to previous month" class="inline-flex items-center justify-center h-11 w-11 rounded-md border border-input bg-background hover:bg-accent">
      <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m15 18-6-6 6-6"/></svg>
    </button>
    <span class="text-sm font-medium">{monthLabel}</span>
    <button onclick={nextMonth} aria-label="Go to next month" class="inline-flex items-center justify-center h-11 w-11 rounded-md border border-input bg-background hover:bg-accent">
      <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m9 18 6-6-6-6"/></svg>
    </button>
  </div>
  <div class="grid grid-cols-7 gap-1 mb-1">
    {#each dayNames as day}
      <div class="text-center text-xs text-muted-foreground">{day}</div>
    {/each}
  </div>
  <div class="grid grid-cols-7 gap-1">
    {#each Array(leadingBlanks) as _}
      <div></div>
    {/each}
    {#each Array(daysInMonth) as _, i}
      {@const d = i + 1}
      <button onclick={() => selectDay(d)} class={['h-11 w-11 rounded-md text-sm text-center hover:bg-accent', isSame(d) ? 'bg-primary text-primary-foreground hover:bg-primary' : '', isToday(d) && !isSame(d) ? 'font-bold underline' : ''].join(' ')}>{d}</button>
    {/each}
  </div>
</div>

// packages/ui-vue/src/components/calendar.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import { cn } from '../lib/utils'

const props = defineProps<{ class?: string; locale?: string }>()
const modelValue = defineModel<Date | undefined>()

const today = new Date()
const viewYear = ref(today.getFullYear())
const viewMonth = ref(today.getMonth())

function resolveLocale() {
  return props.locale ?? (typeof navigator !== 'undefined' ? navigator.language : 'en-US')
}

function getWeekStart(locale: string): number {
  try {
    const info = (new Intl.Locale(locale) as unknown as { weekInfo?: { firstDay: number } }).weekInfo
    if (info) return info.firstDay
  } catch { /* ignore */ }
  const table: Record<string, number> = { 'de': 1, 'fr': 1, 'it': 1, 'es': 1, 'ar': 0, 'en': 0 }
  return table[locale.split('-')[0]] ?? 0
}

const weekStart = computed(() => getWeekStart(resolveLocale()))

const dayNames = computed(() => {
  const loc = resolveLocale()
  const fmt = new Intl.DateTimeFormat(loc, { weekday: 'short' })
  const ws = weekStart.value
  // 2024-01-07 = Sunday
  const sunBased = Array.from({ length: 7 }, (_, i) => fmt.format(new Date(2024, 0, 7 + i)))
  return [...sunBased.slice(ws), ...sunBased.slice(0, ws)]
})

const title = computed(() =>
  new Intl.DateTimeFormat(resolveLocale(), { month: 'long', year: 'numeric' })
    .format(new Date(viewYear.value, viewMonth.value, 1))
)

const days = computed(() => {
  const ws = weekStart.value
  const firstDow = new Date(viewYear.value, viewMonth.value, 1).getDay()
  const leading = ((firstDow - ws + 7) % 7)
  const total = new Date(viewYear.value, viewMonth.value + 1, 0).getDate()
  const cells: (number | null)[] = Array(leading).fill(null)
  for (let d = 1; d <= total; d++) cells.push(d)
  while (cells.length % 7 !== 0) cells.push(null)
  return cells
})

function prevMonth() {
  if (viewMonth.value === 0) { viewMonth.value = 11; viewYear.value-- }
  else viewMonth.value--
}
function nextMonth() {
  if (viewMonth.value === 11) { viewMonth.value = 0; viewYear.value++ }
  else viewMonth.value++
}
function select(day: number | null) {
  if (!day) return
  modelValue.value = new Date(viewYear.value, viewMonth.value, day)
}
function isSelected(day: number | null) {
  if (!day || !modelValue.value) return false
  const d = modelValue.value
  return d.getFullYear() === viewYear.value && d.getMonth() === viewMonth.value && d.getDate() === day
}
function isToday(day: number | null) {
  if (!day) return false
  return today.getFullYear() === viewYear.value && today.getMonth() === viewMonth.value && today.getDate() === day
}
</script>

<template>
  <div :class="cn('p-3 rounded-md border', props.class)">
    <div class="flex items-center justify-between mb-2">
      <button @click="prevMonth" class="inline-flex items-center justify-center h-11 w-11 rounded-md border hover:bg-accent">
        <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m15 18-6-6 6-6"/></svg>
      </button>
      <span class="text-sm font-medium">{{ title }}</span>
      <button @click="nextMonth" class="inline-flex items-center justify-center h-11 w-11 rounded-md border hover:bg-accent">
        <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m9 18 6-6-6-6"/></svg>
      </button>
    </div>
    <div class="grid grid-cols-7 gap-1 mb-1">
      <div v-for="d in dayNames" :key="d" class="text-center text-xs text-muted-foreground font-medium h-7 flex items-center justify-center">{{ d }}</div>
    </div>
    <div class="grid grid-cols-7 gap-1">
      <button
        v-for="(day, i) in days"
        :key="i"
        :disabled="!day"
        @click="select(day)"
        :class="cn(
          'h-11 w-11 rounded-md text-sm flex items-center justify-center transition-colors',
          !day ? 'invisible' : '',
          isSelected(day) ? 'bg-primary text-primary-foreground hover:bg-primary/90' : '',
          isToday(day) && !isSelected(day) ? 'bg-accent text-accent-foreground' : '',
          day && !isSelected(day) && !isToday(day) ? 'hover:bg-accent hover:text-accent-foreground' : ''
        )"
      >
        {{ day }}
      </button>
    </div>
  </div>
</template>
