// packages/ui-svelte/src/lib/components/CardHeader.svelte
<script lang="ts">
  /** Top section of a Card, containing CardTitle and CardDescription. */
  import { cn } from '../utils'
  interface Props { class?: string; children?: import('svelte').Snippet }
  const { class: cls = '', children }: Props = $props()
</script>
<div class={cn('flex flex-col space-y-1.5 p-6', cls)}>{@render children?.()}</div>

// packages/ui-vue/src/components/card-header.vue
<script setup lang="ts">
import { cn } from '@/lib/utils'
/** Top section of a Card, typically containing CardTitle and CardDescription. */
defineOptions({ name: 'CardHeader' })
const props = defineProps<{ class?: string }>()
</script>
<template><div :class="cn('flex flex-col space-y-1.5 p-6', props.class)"><slot /></div></template>
