// packages/ui-svelte/src/lib/components/CardFooter.svelte
<script lang="ts">
  /** Bottom section of a Card, typically containing action buttons. */
  import { cn } from '../utils'
  interface Props { class?: string; children?: import('svelte').Snippet }
  const { class: cls = '', children }: Props = $props()
</script>
<div class={cn('flex items-center p-6 pt-0', cls)}>{@render children?.()}</div>

// packages/ui-vue/src/components/card-footer.vue
<script setup lang="ts">
import { cn } from '@/lib/utils'
/** Bottom section of a Card, typically containing action buttons. */
defineOptions({ name: 'CardFooter' })
const props = defineProps<{ class?: string }>()
</script>
<template><div :class="cn('flex items-center p-6 pt-0', props.class)"><slot /></div></template>
