// packages/ui/src/components/checkbox.tsx
import * as React from 'react'
import * as CheckboxPrimitive from '@radix-ui/react-checkbox'
import { Check } from 'lucide-react'
import { cn } from '@/lib/utils'

/**
 * A styled checkbox control built on Radix UI CheckboxPrimitive.
 * Accepts all Radix Checkbox.Root props including `checked`, `defaultChecked`, `onCheckedChange`, and `disabled`.
 *
 * @accessibility Touch target is 24×24px (WCAG 2.5.8 AA). For strict AAA (44×44px),
 *   wrap with a larger clickable area or use inside a `<label>` that extends the hit region.
 */
const Checkbox = React.forwardRef<
  React.ElementRef<typeof CheckboxPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof CheckboxPrimitive.Root>
>(({ className, ...props }, ref) => (
  <CheckboxPrimitive.Root
    ref={ref}
    className={cn(
      'peer h-6 w-6 shrink-0 rounded-sm border border-primary shadow focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:bg-primary data-[state=checked]:text-primary-foreground',
      className
    )}
    {...props}
  >
    <CheckboxPrimitive.Indicator
      className={cn('flex items-center justify-center text-current')}
    >
      <Check className="h-4 w-4" />
    </CheckboxPrimitive.Indicator>
  </CheckboxPrimitive.Root>
))
Checkbox.displayName = CheckboxPrimitive.Root.displayName

export { Checkbox }

// packages/ui-vue/src/components/checkbox.vue
<script setup lang="ts">
import { CheckboxRoot, CheckboxIndicator, type CheckboxRootProps } from 'radix-vue'
import { Check } from 'lucide-vue-next'
import { cn } from '@/lib/utils'
/**
 * Checkbox — accessible checkbox control backed by Radix Vue.
 *
 * @example
 * ```vue
 * <Checkbox id="terms" v-model:checked="accepted" />
 * <label for="terms">Accept terms and conditions</label>
 * ```
 *
 * @accessibility Fully keyboard-navigable. Supports indeterminate state via `checked="indeterminate"`.
 * Touch target is 24×24px (WCAG 2.5.8 AA). For strict AAA (44×44px),
 * wrap with a larger clickable area or use inside a `<label>` that extends the hit region.
 */
defineOptions({ name: 'Checkbox' })
const props = defineProps<{ class?: string }>()
</script>
<template>
  <CheckboxRoot v-bind="props" :class="cn('peer h-6 w-6 shrink-0 rounded-sm border border-primary shadow focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:bg-primary data-[state=checked]:text-primary-foreground', props.class)">
    <CheckboxIndicator class="flex items-center justify-center text-current"><Check class="h-4 w-4" /></CheckboxIndicator>
  </CheckboxRoot>
</template>
