// packages/ui-svelte/src/lib/components/Collapsible.svelte
<script lang="ts">
  /**
   * Collapsible — expandable/collapsible region backed by Melt UI.
   *
   * @example
   * ```svelte
   * <Collapsible>
   *   <CollapsibleTrigger>Toggle</CollapsibleTrigger>
   *   <CollapsibleContent>Hidden content</CollapsibleContent>
   * </Collapsible>
   * ```
   */
  import { createCollapsible, melt } from '@melt-ui/svelte'
  import { setContext } from 'svelte'

  interface Props {
    open?: boolean
    class?: string
    children?: import('svelte').Snippet
  }
  const { open = false, class: cls = '', children }: Props = $props()

  const collapsible = createCollapsible({ defaultOpen: false })
  $effect(() => { collapsible.states.open.set(open) })
  setContext('paul-collapsible', collapsible)
</script>
<div use:melt={collapsible.elements.root} class={cls}>{@render children?.()}</div>

// packages/ui-vue/src/components/collapsible.vue
<script setup lang="ts">
import { CollapsibleRoot, type CollapsibleRootProps } from 'radix-vue'
/**
 * Collapsible — root container for an expandable/collapsible region.
 *
 * @example
 * ```vue
 * <Collapsible v-model:open="isOpen">
 *   <CollapsibleTrigger>Toggle</CollapsibleTrigger>
 *   <CollapsibleContent>Hidden content</CollapsibleContent>
 * </Collapsible>
 * ```
 */
defineOptions({ name: 'Collapsible' })
const props = defineProps<{}>()
</script>
<template><CollapsibleRoot v-bind="props"><slot /></CollapsibleRoot></template>
