// packages/ui-angular/src/lib/dialog/dialog-description.component.ts
import { Component, Input, HostBinding, ChangeDetectionStrategy } from '@angular/core'
import { cn } from '../../lib/utils'

/** Supporting description text rendered below DialogTitle. */
@Component({ selector: 'paul-dialog-description', standalone: true, template: `<ng-content />`, changeDetection: ChangeDetectionStrategy.OnPush })
export class DialogDescriptionComponent {
  @Input() class = ''
  @HostBinding('class') get hostClass() { return cn('text-sm text-muted-foreground', this.class) }
}

// packages/ui-vue/src/components/dialog-description.vue
<script setup lang="ts">
import { DialogDescription } from 'radix-vue'
import { cn } from '@/lib/utils'
/** Optional supporting description rendered below DialogTitle. */
defineOptions({ name: 'DialogDescription' })
const props = defineProps<{ class?: string }>()
</script>
<template><DialogDescription :class="cn('text-sm text-muted-foreground', props.class)"><slot /></DialogDescription></template>
