// packages/ui-svelte/src/lib/components/DropdownMenuItem.svelte
<script lang="ts">
  let { class: className = '', disabled = false, onclick, ...props } = $props()
</script>
<div role="menuitem" {onclick} class={['relative flex cursor-default select-none items-center rounded-sm px-2 py-1.5 text-sm outline-none transition-colors hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground data-[disabled]:pointer-events-none data-[disabled]:opacity-50', className].join(' ')} data-disabled={disabled || undefined} {...props}><slot /></div>

// packages/ui-vue/src/components/dropdown-menu-item.vue
<script setup lang="ts">
import { DropdownMenuItem, type DropdownMenuItemProps } from 'radix-vue'
import { cn } from '@/lib/utils'
/** A single selectable item inside DropdownMenuContent. Use `inset` to indent when mixed with icons. */
defineOptions({ name: 'DropdownMenuItem' })
const props = defineProps<{ class?: string; inset?: boolean }>()
</script>
<template><DropdownMenuItem v-bind="props" :class="cn('relative flex cursor-default select-none items-center gap-2 rounded-sm px-2 py-1.5 text-sm outline-none transition-colors focus:bg-accent focus:text-accent-foreground data-[disabled]:pointer-events-none data-[disabled]:opacity-50', props.inset && 'pl-8', props.class)"><slot /></DropdownMenuItem></template>
