// packages/ui-svelte/src/lib/components/Field.svelte
<script lang="ts">
  /**
   * Field — form field wrapper wiring a label, hint, and error to its input.
   *
   * @example
   * ```svelte
   * <Field label="Email" hint="We'll never share it." error={errors.email} required>
   *   {#snippet input({ id })}
   *     <Input {id} type="email" bind:value={email} />
   *   {/snippet}
   * </Field>
   * ```
   *
   * @accessibility Label is programmatically linked to the input via matching for/id.
   */
  import { cn } from '../utils'
  const uid = Math.random().toString(36).slice(2, 9)
  interface Props {
    label?: string
    hint?: string
    error?: string
    required?: boolean
    id?: string
    class?: string
    input?: import('svelte').Snippet<[{ id: string; describedBy?: string }]>
    children?: import('svelte').Snippet
  }
  const { label = '', hint = '', error = '', required = false, id = `field-${uid}`, class: cls = '', input, children }: Props = $props()
  const hintId = `${id}-hint`
  const errorId = `${id}-error`
  const describedBy = error ? errorId : hint ? hintId : undefined
</script>
<div class={cn('flex flex-col gap-1.5', cls)}>
  {#if label}
    <label for={id} class="text-sm font-medium leading-none">
      {label}{#if required}<span class="text-destructive-text ml-0.5" aria-hidden="true">*</span>{/if}
    </label>
  {/if}
  {#if input}
    {@render input({ id, describedBy })}
  {:else}
    {@render children?.()}
  {/if}
  {#if hint && !error}<p id={hintId} class="text-sm text-muted-foreground">{hint}</p>{/if}
  {#if error}<p id={errorId} class="text-sm text-destructive-text" role="alert">{error}</p>{/if}
</div>

// packages/ui-vue/src/components/field.vue
<script setup lang="ts">
import { useId, computed } from 'vue'
import { cn } from '@/lib/utils'
/**
 * Field — form field wrapper that wires a label, hint, and error message to its input child.
 *
 * Passes the generated `id` to the default slot so the input can be associated with the label.
 *
 * @example
 * ```vue
 * <Field label="Email" hint="We'll never share your email." :error="errors.email" required>
 *   <template #default="{ id }">
 *     <Input :id="id" v-model="email" type="email" />
 *   </template>
 * </Field>
 * ```
 *
 * @accessibility The label is programmatically linked to the input via matching `for`/`id`.
 * Error messages use `text-destructive-text` and should also be linked via `aria-describedby`.
 */
defineOptions({ name: 'Field' })
const props = defineProps<{ label?: string; error?: string; hint?: string; required?: boolean; class?: string }>()
const id = useId()
const hintId = `${id}-hint`
const errorId = `${id}-error`
const describedBy = computed(() => props.error ? errorId : props.hint ? hintId : undefined)
</script>
<template>
  <div :class="cn('space-y-2', props.class)">
    <label v-if="props.label" :for="id" class="text-sm font-medium leading-none">{{ props.label }}<span v-if="props.required" class="text-destructive-text ml-1">*</span></label>
    <slot :id="id" :describedBy="describedBy" />
    <p v-if="props.error" :id="errorId" class="text-[0.8rem] font-medium text-destructive-text">{{ props.error }}</p>
    <p v-else-if="props.hint" :id="hintId" class="text-[0.8rem] text-muted-foreground">{{ props.hint }}</p>
  </div>
</template>
