// packages/ui-angular/src/lib/label/label.component.ts
import { Component, Input, HostBinding, ChangeDetectionStrategy } from '@angular/core'
import { cn } from '../../lib/utils'

/**
 * Label — accessible form label.
 *
 * @example
 * ```html
 * <label paul-label for="email">Email address</label>
 * <input paul-input id="email" type="email" />
 * ```
 */
@Component({
  selector: 'label[paul-label]',
  standalone: true,
  template: `<ng-content />`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class LabelComponent {
  @Input() class = ''
  @HostBinding('class') get hostClass() {
    return cn('text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70', this.class)
  }
}

// packages/ui-vue/src/components/label.vue
<script setup lang="ts">
import { Label as LabelRoot } from 'radix-vue'
import { cn } from '@/lib/utils'
/**
 * Label — accessible form label backed by Radix Vue LabelRoot.
 *
 * Automatically prevents text selection on double-click of associated controls.
 *
 * @example
 * ```vue
 * <Label for="email">Email address</Label>
 * <Input id="email" type="email" />
 * ```
 */
defineOptions({ name: 'Label' })
const props = defineProps<{ for?: string; class?: string }>()
</script>
<template><LabelRoot v-bind="props" :class="cn('text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70', props.class)"><slot /></LabelRoot></template>
