// packages/ui-svelte/src/lib/components/Label.svelte
<script lang="ts">
  /**
   * Label — accessible form label backed by Melt UI.
   *
   * @example
   * ```svelte
   * <Label for="email">Email address</Label>
   * <Input id="email" type="email" bind:value={email} />
   * ```
   */
  import { createLabel, melt } from '@melt-ui/svelte'
  import { cn } from '../utils'

  interface Props { for?: string; class?: string; children?: import('svelte').Snippet }
  const { for: forId, class: cls = '', children }: Props = $props()

  const { elements: { root } } = createLabel()
</script>
<label use:melt={root} for={forId} class={cn('text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70', cls)}>
  {@render children?.()}
</label>

// packages/ui-vue/src/components/label.vue
<script setup lang="ts">
import { Label as LabelRoot } from 'radix-vue'
import { cn } from '@/lib/utils'
/**
 * Label — accessible form label backed by Radix Vue LabelRoot.
 *
 * Automatically prevents text selection on double-click of associated controls.
 *
 * @example
 * ```vue
 * <Label for="email">Email address</Label>
 * <Input id="email" type="email" />
 * ```
 */
defineOptions({ name: 'Label' })
const props = defineProps<{ for?: string; class?: string }>()
</script>
<template><LabelRoot v-bind="props" :class="cn('text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70', props.class)"><slot /></LabelRoot></template>
