// packages/ui-svelte/src/lib/components/PaginationPrevious.svelte
<script lang="ts">
  let { href = '#', class: className = '', ...props } = $props()
</script>
<a {href} aria-label="Go to previous page" class={['inline-flex items-center gap-1 pl-2.5 h-10 px-4 py-2 rounded-md text-sm font-medium hover:bg-accent hover:text-accent-foreground', className].join(' ')} {...props}>
  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m15 18-6-6 6-6"/></svg>
  <span>Previous</span>
</a>

// packages/ui-vue/src/components/pagination-previous.vue
<script setup lang="ts">
import { cn } from '../lib/utils'
const props = defineProps<{ href?: string; class?: string }>()
</script>

<template>
  <a
    :href="props.href"
    aria-label="Go to previous page"
    :class="cn('inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 hover:bg-accent hover:text-accent-foreground h-9 px-4 gap-1 pl-2.5', props.class)"
  >
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m15 18-6-6 6-6"/></svg>
    <span>Previous</span>
  </a>
</template>
