// packages/ui-svelte/src/lib/components/Progress.svelte
<script lang="ts">
  /**
   * Progress — linear progress bar backed by Melt UI.
   *
   * @example
   * ```svelte
   * <Progress value={75} />
   * ```
   *
   * @accessibility Sets role="progressbar" and aria-valuenow automatically.
   */
  import { createProgress, melt } from '@melt-ui/svelte'
  import { cn } from '../utils'

  interface Props { value?: number; max?: number; class?: string }
  const { value = 0, max = 100, class: cls = '' }: Props = $props()

  const { elements: { root, range }, options } = createProgress({ max: 100, value: 0 })
  $effect(() => { options.value.set(value); options.max.set(max) })
</script>
<div use:melt={root} class={cn('relative h-2 w-full overflow-hidden rounded-full bg-primary/20', cls)}>
  <div use:melt={range} class="h-full bg-primary transition-all"></div>
</div>

// packages/ui-vue/src/components/progress.vue
<script setup lang="ts">
import { ProgressRoot, ProgressIndicator, type ProgressRootProps } from 'radix-vue'
import { cn } from '@/lib/utils'
/**
 * Progress — linear progress bar indicating completion of an operation.
 *
 * @example
 * ```vue
 * <Progress :model-value="75" />
 * ```
 *
 * @accessibility Backed by Radix Vue ProgressRoot which sets `role="progressbar"` and
 * `aria-valuenow` automatically.
 */
defineOptions({ name: 'Progress' })
const props = defineProps<{ modelValue?: number; max?: number; class?: string }>()
</script>
<template>
  <ProgressRoot v-bind="props" :class="cn('relative h-2 w-full overflow-hidden rounded-full bg-primary/20', props.class)">
    <ProgressIndicator class="h-full w-full flex-1 bg-primary transition-all" :style="{ transform: `translateX(-${100 - (props.modelValue ?? 0)}%)` }" />
  </ProgressRoot>
</template>
