// packages/ui/src/components/progress.tsx
import * as React from 'react'
import * as ProgressPrimitive from '@radix-ui/react-progress'
import { cn } from '@/lib/utils'

/**
 * A styled progress bar built on Radix UI ProgressPrimitive.
 * Key props: `value` (0–100) representing the current progress percentage.
 */
const Progress = React.forwardRef<
  React.ElementRef<typeof ProgressPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof ProgressPrimitive.Root>
>(({ className, value, ...props }, ref) => (
  <ProgressPrimitive.Root
    ref={ref}
    className={cn(
      'relative h-2 w-full overflow-hidden rounded-full bg-primary/20',
      className
    )}
    {...props}
  >
    <ProgressPrimitive.Indicator
      className="h-full w-full flex-1 bg-primary transition-all"
      style={{ transform: `translateX(-${100 - (value || 0)}%)` }}
    />
  </ProgressPrimitive.Root>
))
Progress.displayName = ProgressPrimitive.Root.displayName

export { Progress }

// packages/ui-vue/src/components/progress.vue
<script setup lang="ts">
import { ProgressRoot, ProgressIndicator, type ProgressRootProps } from 'radix-vue'
import { cn } from '@/lib/utils'
/**
 * Progress — linear progress bar indicating completion of an operation.
 *
 * @example
 * ```vue
 * <Progress :model-value="75" />
 * ```
 *
 * @accessibility Backed by Radix Vue ProgressRoot which sets `role="progressbar"` and
 * `aria-valuenow` automatically.
 */
defineOptions({ name: 'Progress' })
const props = defineProps<{ class?: string }>()
</script>
<template>
  <ProgressRoot v-bind="props" :class="cn('relative h-2 w-full overflow-hidden rounded-full bg-primary/20', props.class)">
    <ProgressIndicator class="h-full w-full flex-1 bg-primary transition-all" :style="{ transform: `translateX(-${100 - (props.modelValue ?? 0)}%)` }" />
  </ProgressRoot>
</template>
