// packages/ui-svelte/src/lib/components/SelectItem.svelte
<script lang="ts">
  /** A single selectable option inside Select. Shows a checkmark when selected. */
  import { getContext } from 'svelte'
  import { melt } from '@melt-ui/svelte'
  import { cn } from '../utils'

  interface Props { value: string; disabled?: boolean; class?: string; children?: import('svelte').Snippet }
  const { value, disabled = false, class: cls = '', children }: Props = $props()
  const select = getContext<ReturnType<typeof import('@melt-ui/svelte').createSelect>>('paul-select')
</script>
<div
  use:melt={select.elements.option({ value, label: typeof children === 'function' ? value : value, disabled })}
  class={cn('relative flex w-full cursor-pointer select-none items-center rounded-sm py-1.5 pl-2 pr-8 text-sm outline-none data-[highlighted]:bg-accent data-[highlighted]:text-accent-foreground data-[disabled]:pointer-events-none data-[disabled]:opacity-50', cls)}
>
  {@render children?.()}
</div>

// packages/ui-vue/src/components/select-item.vue
<script setup lang="ts">
import { SelectItem, SelectItemText, SelectItemIndicator, type SelectItemProps } from 'radix-vue'
import { Check } from 'lucide-vue-next'
import { cn } from '@/lib/utils'
/** A single selectable option inside SelectContent. Shows a checkmark when selected. */
defineOptions({ name: 'SelectItem' })
const props = defineProps<{ value: string; disabled?: boolean; textValue?: string; class?: string }>()
</script>
<template>
  <SelectItem v-bind="props" :class="cn('relative flex w-full cursor-default select-none items-center rounded-sm py-1.5 pl-2 pr-8 text-sm outline-none focus:bg-accent data-[disabled]:pointer-events-none data-[disabled]:opacity-50', props.class)">
    <span class="absolute right-2 flex h-3.5 w-3.5 items-center justify-center"><SelectItemIndicator><Check class="h-4 w-4" /></SelectItemIndicator></span>
    <SelectItemText><slot /></SelectItemText>
  </SelectItem>
</template>
