// packages/ui-svelte/src/lib/components/SidebarMenuButton.svelte
<script lang="ts">
  let { isActive = false, class: className = '', onclick, ...props } = $props()
</script>
<button type="button" {onclick} data-active={isActive || undefined} class={['peer/menu-button flex w-full items-center gap-2 overflow-hidden rounded-md p-2 text-left text-sm outline-none ring-sidebar-ring transition-[width,height,padding] hover:bg-sidebar-accent hover:text-sidebar-accent-foreground focus-visible:ring-2 active:bg-sidebar-accent active:text-sidebar-accent-foreground disabled:pointer-events-none disabled:opacity-50 data-[active=true]:bg-sidebar-accent data-[active=true]:font-medium data-[active=true]:text-sidebar-accent-foreground', className].join(' ')} {...props}><slot /></button>

// packages/ui-vue/src/components/sidebar-menu-button.vue
<script setup lang="ts">
import { cn } from '../lib/utils'
const props = defineProps<{ isActive?: boolean; class?: string }>()
</script>
<template>
  <button :class="cn('flex w-full items-center gap-2 overflow-hidden rounded-md p-2 text-left text-sm outline-none ring-sidebar-ring transition-colors hover:bg-sidebar-accent hover:text-sidebar-accent-foreground focus-visible:ring-2 active:bg-sidebar-accent active:text-sidebar-accent-foreground', props.isActive ? 'bg-sidebar-accent font-medium text-sidebar-accent-foreground' : '', props.class)">
    <slot />
  </button>
</template>
