// packages/ui/src/components/switch.tsx
import * as React from 'react'
import * as SwitchPrimitives from '@radix-ui/react-switch'
import { cn } from '@/lib/utils'

/**
 * A styled toggle switch built on Radix UI SwitchPrimitive.
 * Accepts all Radix Switch.Root props including `checked`, `defaultChecked`, `onCheckedChange`, and `disabled`.
 *
 * @accessibility Track is 24×44px (WCAG 2.5.8 AA). For strict AAA (44×44px),
 *   wrap with padding or use a larger container that extends the clickable region.
 */
const Switch = React.forwardRef<
  React.ElementRef<typeof SwitchPrimitives.Root>,
  React.ComponentPropsWithoutRef<typeof SwitchPrimitives.Root>
>(({ className, ...props }, ref) => (
  <SwitchPrimitives.Root
    className={cn(
      'peer inline-flex h-6 w-11 shrink-0 cursor-pointer items-center rounded-full border-2 border-transparent shadow-sm transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:ring-offset-background disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:bg-primary data-[state=unchecked]:bg-input',
      className
    )}
    {...props}
    ref={ref}
  >
    <SwitchPrimitives.Thumb
      className={cn(
        'pointer-events-none block h-5 w-5 rounded-full bg-background shadow-lg ring-0 transition-transform data-[state=checked]:translate-x-6 data-[state=unchecked]:translate-x-0'
      )}
    />
  </SwitchPrimitives.Root>
))
Switch.displayName = SwitchPrimitives.Root.displayName

export { Switch }

// packages/ui-vue/src/components/switch.vue
<script setup lang="ts">
import { SwitchRoot, SwitchThumb, type SwitchRootProps } from 'radix-vue'
import { cn } from '@/lib/utils'
/**
 * Switch — toggle switch for binary on/off settings.
 *
 * @example
 * ```vue
 * <Switch id="airplane" v-model:checked="airplaneMode" />
 * <Label for="airplane">Airplane Mode</Label>
 * ```
 *
 * @accessibility Backed by Radix Vue SwitchRoot. Reports `role="switch"` with `aria-checked`.
 * Track is 24×44px (WCAG 2.5.8 AA). For strict AAA (44×44px),
 * wrap with padding or use a larger container that extends the clickable region.
 */
defineOptions({ name: 'Switch' })
const props = defineProps<{ class?: string }>()
</script>
<template>
  <SwitchRoot v-bind="props" :class="cn('peer inline-flex h-6 w-11 shrink-0 cursor-pointer items-center rounded-full border-2 border-transparent shadow-sm transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:bg-primary data-[state=unchecked]:bg-input', props.class)">
    <SwitchThumb class="pointer-events-none block h-5 w-5 rounded-full bg-background shadow-lg ring-0 transition-transform data-[state=checked]:translate-x-6 data-[state=unchecked]:translate-x-0" />
  </SwitchRoot>
</template>
