// packages/ui-svelte/src/lib/components/TabsList.svelte
<script lang="ts">
  /** Container for TabsTrigger buttons, styled as a segmented control. */
  import { getContext } from 'svelte'
  import { melt } from '@melt-ui/svelte'
  import { cn } from '../utils'
  interface Props { class?: string; children?: import('svelte').Snippet }
  const { class: cls = '', children }: Props = $props()
  const tabs = getContext<ReturnType<typeof import('@melt-ui/svelte').createTabs>>('paul-tabs')
</script>
<div use:melt={tabs.elements.list} class={cn('inline-flex h-9 items-center justify-center rounded-lg bg-muted p-1 text-muted-foreground', cls)}>
  {@render children?.()}
</div>

// packages/ui-vue/src/components/tabs-list.vue
<script setup lang="ts">
import { TabsList } from 'radix-vue'
import { cn } from '@/lib/utils'
/** Container for TabsTrigger buttons, styled as a segmented control. */
defineOptions({ name: 'TabsList' })
const props = defineProps<{ class?: string }>()
</script>
<template><TabsList :class="cn('inline-flex h-11 items-center justify-center rounded-lg bg-muted p-1 text-muted-foreground', props.class)"><slot /></TabsList></template>
