// packages/ui-angular/src/lib/tabs/tabs-list.component.ts
import { Component, Input, HostBinding, ChangeDetectionStrategy } from '@angular/core'
import { cn } from '../../lib/utils'

/** Container for TabsTrigger buttons, styled as a segmented control. */
@Component({ selector: 'paul-tabs-list', standalone: true, template: `<ng-content />`, changeDetection: ChangeDetectionStrategy.OnPush })
export class TabsListComponent {
  @Input() class = ''
  @HostBinding('class') get hostClass() {
    return cn('inline-flex h-9 items-center justify-center rounded-lg bg-muted p-1 text-muted-foreground', this.class)
  }
  @HostBinding('attr.role') role = 'tablist'
}

// packages/ui-vue/src/components/tabs-list.vue
<script setup lang="ts">
import { TabsList } from 'radix-vue'
import { cn } from '@/lib/utils'
/** Container for TabsTrigger buttons, styled as a segmented control. */
defineOptions({ name: 'TabsList' })
const props = defineProps<{ class?: string }>()
</script>
<template><TabsList :class="cn('inline-flex h-11 items-center justify-center rounded-lg bg-muted p-1 text-muted-foreground', props.class)"><slot /></TabsList></template>
