// packages/ui-svelte/src/lib/components/ToastViewport.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  let { class: className = '', children, ...props} = $props()
</script>
<div class={['fixed top-0 z-[100] flex max-h-screen w-full flex-col-reverse p-4 sm:bottom-0 sm:end-0 sm:top-auto sm:flex-col md:max-w-[420px]', className].join(' ')} {...props}>{@render children?.()}</div>

// packages/ui-vue/src/components/toast-viewport.vue
<script setup lang="ts">
import { cn } from '../lib/utils'
const props = defineProps<{ class?: string }>()
</script>
<template>
  <div :class="cn('fixed top-0 z-[100] flex max-h-screen w-full flex-col-reverse p-4 sm:bottom-0 sm:end-0 sm:top-auto sm:flex-col md:max-w-[420px]', props.class)">
    <slot />
  </div>
</template>
