// packages/ui-svelte/src/lib/components/ToggleGroupItem.svelte
<script lang="ts">
  let { value = '', pressed = $bindable(false), class: className = '', onclick, ...props } = $props()
</script>
<button type="button" role="radio" aria-checked={pressed} {onclick} class={['inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors hover:bg-muted hover:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 data-[state=on]:bg-accent data-[state=on]:text-accent-foreground h-10 px-3', className].join(' ')} data-state={pressed ? 'on' : 'off'} {...props}><slot /></button>

// packages/ui-vue/src/components/toggle-group-item.vue
<script setup lang="ts">
import { ToggleGroupItem, type ToggleGroupItemProps } from 'radix-vue'
import { cn } from '@/lib/utils'
/** Individual toggle button inside a ToggleGroup. Requires a unique `value` prop. */
defineOptions({ name: 'ToggleGroupItem' })
const props = defineProps<{ value: string; class?: string; disabled?: boolean }>()
</script>
<template><ToggleGroupItem v-bind="props" :class="cn('inline-flex items-center justify-center rounded-md text-sm font-medium transition-colors hover:bg-muted disabled:pointer-events-none disabled:opacity-50 data-[state=on]:bg-accent data-[state=on]:text-accent-foreground h-9 px-3', props.class)"><slot /></ToggleGroupItem></template>
