// packages/ui-vue/src/components/dialog-title.vue
<script setup lang="ts">
import { DialogTitle } from 'radix-vue'
import { cn } from '@/lib/utils'
/** Accessible title for the Dialog. Required for screen reader announcement. */
defineOptions({ name: 'DialogTitle' })
const props = defineProps<{ class?: string }>()
</script>
<template><DialogTitle :class="cn('text-lg font-semibold leading-none tracking-tight', props.class)"><slot /></DialogTitle></template>

// packages/ui-angular/src/lib/dialog/dialog-title.component.ts
import { Component, Input, HostBinding, ChangeDetectionStrategy } from '@angular/core'
import { cn } from '../../lib/utils'

/** Accessible title for the dialog, announced by screen readers. */
@Component({ selector: 'paul-dialog-title', standalone: true, template: `<ng-content />`, changeDetection: ChangeDetectionStrategy.OnPush })
export class DialogTitleComponent {
  @Input() class = ''
  @HostBinding('class') get hostClass() { return cn('text-lg font-semibold leading-none tracking-tight', this.class) }
}
