// packages/ui-svelte/src/lib/components/DialogHeader.svelte
<script lang="ts">
  /** Layout wrapper for the dialog title and description at the top. */
  import { cn } from '../utils'
  interface Props { class?: string; children?: import('svelte').Snippet }
  const { class: cls = '', children }: Props = $props()
</script>
<div class={cn('flex flex-col space-y-1.5 text-center sm:text-left', cls)}>{@render children?.()}</div>

// packages/ui-angular/src/lib/dialog/dialog-header.component.ts
import { Component, Input, HostBinding, ChangeDetectionStrategy } from '@angular/core'
import { cn } from '../../lib/utils'

/** Layout wrapper for the dialog title and description at the top. */
@Component({ selector: 'paul-dialog-header', standalone: true, template: `<ng-content />`, changeDetection: ChangeDetectionStrategy.OnPush })
export class DialogHeaderComponent {
  @Input() class = ''
  @HostBinding('class') get hostClass() { return cn('flex flex-col space-y-1.5 text-center sm:text-left', this.class) }
}
