// packages/ui-svelte/src/lib/components/Field.svelte
<script lang="ts">
  /**
   * Field — form field wrapper wiring a label, hint, and error to its input.
   *
   * @example
   * ```svelte
   * <Field label="Email" hint="We'll never share it." error={errors.email} required>
   *   {#snippet input({ id })}
   *     <Input {id} type="email" bind:value={email} />
   *   {/snippet}
   * </Field>
   * ```
   *
   * @accessibility Label is programmatically linked to the input via matching for/id.
   */
  import { cn } from '../utils'
  const uid = Math.random().toString(36).slice(2, 9)
  interface Props {
    label?: string
    hint?: string
    error?: string
    required?: boolean
    id?: string
    class?: string
    input?: import('svelte').Snippet<[{ id: string; describedBy?: string }]>
    children?: import('svelte').Snippet
  }
  const { label = '', hint = '', error = '', required = false, id = `field-${uid}`, class: cls = '', input, children }: Props = $props()
  const hintId = `${id}-hint`
  const errorId = `${id}-error`
  const describedBy = error ? errorId : hint ? hintId : undefined
</script>
<div class={cn('flex flex-col gap-1.5', cls)}>
  {#if label}
    <label for={id} class="text-sm font-medium leading-none">
      {label}{#if required}<span class="text-destructive-text ml-0.5" aria-hidden="true">*</span>{/if}
    </label>
  {/if}
  {#if input}
    {@render input({ id, describedBy })}
  {:else}
    {@render children?.()}
  {/if}
  {#if hint && !error}<p id={hintId} class="text-sm text-muted-foreground">{hint}</p>{/if}
  {#if error}<p id={errorId} class="text-sm text-destructive-text" role="alert">{error}</p>{/if}
</div>

// packages/ui-angular/src/lib/field/field.component.ts
import { Component, Input, OnInit, ChangeDetectionStrategy } from '@angular/core'
import { CommonModule } from '@angular/common'

/**
 * Field — form field wrapper wiring a label, hint, and error to its input.
 *
 * @example
 * ```html
 * <paul-field label="Email" hint="We'll never share your email." [error]="errors.email" [required]="true">
 *   <input paul-input type="email" [(ngModel)]="email" />
 * </paul-field>
 * ```
 */
@Component({
  selector: 'paul-field',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="flex flex-col gap-1.5">
      <label *ngIf="label" [for]="fieldId" class="text-sm font-medium leading-none">
        {{ label }}<span *ngIf="required" class="text-destructive-text ml-0.5" aria-hidden="true">*</span>
      </label>
      <ng-content />
      <p *ngIf="hint && !error" [id]="hintId" class="text-sm text-muted-foreground">{{ hint }}</p>
      <p *ngIf="error" [id]="errorId" class="text-sm text-destructive-text" role="alert">{{ error }}</p>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class FieldComponent {
  @Input() label = ''
  @Input() hint = ''
  @Input() error = ''
  @Input() required = false
  @Input() fieldId = `field-${Math.random().toString(36).slice(2, 9)}`

  get hintId() { return `${this.fieldId}-hint` }
  get errorId() { return `${this.fieldId}-error` }
  get describedBy() { return this.error ? this.errorId : this.hint ? this.hintId : undefined }
}
