// packages/ui-vue/src/components/label.vue
<script setup lang="ts">
import { Label as LabelRoot } from 'radix-vue'
import { cn } from '@/lib/utils'
/**
 * Label — accessible form label backed by Radix Vue LabelRoot.
 *
 * Automatically prevents text selection on double-click of associated controls.
 *
 * @example
 * ```vue
 * <Label for="email">Email address</Label>
 * <Input id="email" type="email" />
 * ```
 */
defineOptions({ name: 'Label' })
const props = defineProps<{ for?: string; class?: string }>()
</script>
<template><LabelRoot v-bind="props" :class="cn('text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70', props.class)"><slot /></LabelRoot></template>

// packages/ui-react/src/components/label.tsx
import * as React from 'react'
import * as LabelPrimitive from '@radix-ui/react-label'
import { cva, type VariantProps } from 'class-variance-authority'
import { cn } from '@/lib/utils'

const labelVariants = cva(
  'text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70'
)

/**
 * Accessible label built on Radix UI LabelPrimitive.
 * Use `htmlFor` to associate with a form control by its `id`.
 * Automatically dims when the associated control is disabled.
 */
const Label = React.forwardRef<
  React.ElementRef<typeof LabelPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof LabelPrimitive.Root> &
    VariantProps<typeof labelVariants>
>(({ className, ...props }, ref) => (
  <LabelPrimitive.Root
    ref={ref}
    className={cn(labelVariants(), className)}
    {...props}
  />
))
Label.displayName = LabelPrimitive.Root.displayName

export { Label }
