// packages/ui-vue/src/components/skeleton.vue
<script setup lang="ts">
import { cn } from '@/lib/utils'
/**
 * Skeleton — animated loading placeholder that mimics the shape of incoming content.
 *
 * @example
 * ```vue
 * <Skeleton class="h-4 w-[250px]" />
 * <Skeleton class="h-12 w-12 rounded-full" />
 * ```
 */
defineOptions({ name: 'Skeleton' })
const props = defineProps<{ class?: string }>()
</script>
<template><div :class="cn('animate-pulse rounded-md bg-primary/10', props.class)" /></template>

// packages/ui-react/src/components/skeleton.tsx
import { cn } from '@/lib/utils'

/** Animated placeholder block used to indicate loading state. Size and shape are controlled via `className`. */
function Skeleton({
  className,
  ...props
}: React.HTMLAttributes<HTMLDivElement>) {
  return (
    <div
      className={cn('animate-pulse rounded-md bg-primary/10', className)}
      {...props}
    />
  )
}

export { Skeleton }
