// packages/ui-vue/src/components/tooltip.vue
<script setup lang="ts">
import { TooltipProvider, TooltipRoot, TooltipTrigger, TooltipPortal, TooltipContent, type TooltipContentProps } from 'radix-vue'
import { cn } from '@/lib/utils'
/**
 * Tooltip — concise text label that appears on hover/focus to describe an element.
 *
 * @example
 * ```vue
 * <Tooltip content="Save changes">
 *   <Button size="icon"><Save class="h-4 w-4" /></Button>
 * </Tooltip>
 * ```
 *
 * @accessibility The `content` prop becomes the tooltip text. For icon-only triggers also add `aria-label`.
 */
defineOptions({ name: 'Tooltip' })
const props = defineProps<{ content: string; class?: string }>()
</script>
<template>
  <TooltipProvider>
    <TooltipRoot>
      <TooltipTrigger as-child><slot /></TooltipTrigger>
      <TooltipPortal>
        <TooltipContent v-bind="props" :class="cn('z-50 overflow-hidden rounded-md bg-primary px-3 py-1.5 text-xs text-primary-foreground animate-in fade-in-0 zoom-in-95 data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=closed]:zoom-out-95 print:hidden', props.class)">{{ props.content }}</TooltipContent>
      </TooltipPortal>
    </TooltipRoot>
  </TooltipProvider>
</template>

// packages/ui-react/src/components/tooltip.tsx
import * as React from 'react'
import * as TooltipPrimitive from '@radix-ui/react-tooltip'
import { cn } from '@/lib/utils'

/** Wraps the app (or subtree) to provide shared tooltip delay and skip-delay config. */
const TooltipProvider = TooltipPrimitive.Provider

/** Root tooltip. Key props: `open`, `defaultOpen`, `onOpenChange`, `delayDuration`. */
const Tooltip = TooltipPrimitive.Root

/** Element that triggers the tooltip on hover/focus. */
const TooltipTrigger = TooltipPrimitive.Trigger

/** Styled floating content panel. Key props: `side`, `sideOffset`, `align`. @default sideOffset=4 */
const TooltipContent = React.forwardRef<
  React.ElementRef<typeof TooltipPrimitive.Content>,
  React.ComponentPropsWithoutRef<typeof TooltipPrimitive.Content>
>(({ className, sideOffset = 4, ...props }, ref) => (
  <TooltipPrimitive.Content
    ref={ref}
    sideOffset={sideOffset}
    className={cn(
      'z-50 overflow-hidden rounded-md bg-primary px-3 py-1.5 text-xs text-primary-foreground animate-in fade-in-0 zoom-in-95 data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=closed]:zoom-out-95 data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2 print:hidden',
      className
    )}
    {...props}
  />
))
TooltipContent.displayName = TooltipPrimitive.Content.displayName

export { Tooltip, TooltipTrigger, TooltipContent, TooltipProvider }
