// packages/ui-svelte/src/lib/components/InputOTP.svelte
<script lang="ts">
  let { value = $bindable(''), maxLength = 6, class: className = '', ...props } = $props()

  let slots = $derived(Array.from({ length: maxLength }, (_, i) => value[i] ?? ''))
  let inputEl: HTMLInputElement

  function oninput(e: Event) {
    const v = (e.target as HTMLInputElement).value.replace(/\D/g, '').slice(0, maxLength)
    value = v
  }
</script>

<div class={['relative flex items-center gap-2', className].join(' ')} {...props} onclick={() => inputEl?.focus()}>
  <input
    bind:this={inputEl}
    type="text"
    inputmode="numeric"
    autocomplete="one-time-code"
    maxlength={maxLength}
    value={value}
    {oninput}
    aria-label={'Enter one-time password, ' + maxLength + ' digits'}
    class="sr-only"
  />
  {#each slots as slot, i}
    <div
      class={['relative flex h-11 w-11 items-center justify-center border-y border-r border-input text-sm transition-all first:rounded-l-md first:border-l last:rounded-r-md', i === value.length ? 'ring-2 ring-ring ring-offset-background z-10' : ''].join(' ')}
      aria-hidden="true"
    >
      {slot}
      {#if i === value.length}
        <div class="pointer-events-none absolute inset-0 flex items-center justify-center">
          <div class="animate-caret-blink h-4 w-px bg-foreground duration-1000"></div>
        </div>
      {/if}
    </div>
  {/each}
</div>

// packages/ui-angular/src/lib/input-otp/input-otp.component.ts
import { Component, Input, Output, EventEmitter, ChangeDetectionStrategy } from '@angular/core'
import { CommonModule } from '@angular/common'
import { FormsModule } from '@angular/forms'

@Component({
  selector: 'paul-input-otp',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="relative flex items-center gap-2" (click)="realInput.focus()">
      <input #realInput
        type="text"
        inputmode="numeric"
        autocomplete="one-time-code"
        [attr.maxlength]="maxLength"
        [value]="value"
        (input)="onRealInput($event)"
        [attr.aria-label]="'Enter one-time password, ' + maxLength + ' digits'"
        class="sr-only"
      />
      <div *ngFor="let i of slots; let idx = index"
        aria-hidden="true"
        [class]="getSlotClass(idx)"
      >{{ getSlot(idx) }}<span *ngIf="idx === value.length" class="pointer-events-none absolute inset-0 flex items-center justify-center"><span class="animate-caret-blink h-4 w-px bg-foreground duration-1000"></span></span></div>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class InputOTPComponent {
  @Input() maxLength = 6
  @Input() value = ''
  @Output() valueChange = new EventEmitter<string>()

  get slots() { return Array.from({ length: this.maxLength }, (_, i) => i) }
  getSlot(i: number) { return this.value[i] ?? '' }

  getSlotClass(idx: number) {
    const active = idx === this.value.length
    return [
      'relative flex h-11 w-11 items-center justify-center border-y border-e border-input text-sm transition-all',
      idx === 0 ? 'rounded-s-md border-s' : '',
      idx === this.maxLength - 1 ? 'rounded-e-md' : '',
      active ? 'z-10 ring-2 ring-ring ring-offset-background' : '',
    ].join(' ')
  }

  onRealInput(e: Event) {
    const val = (e.target as HTMLInputElement).value.replace(/\D/g, '').slice(0, this.maxLength)
    this.value = val
    this.valueChange.emit(this.value)
  }
}
