// packages/ui-svelte/src/lib/components/HoverCard.svelte
<script lang="ts">
  let { openDelay = 700, class: className = '', ...props } = $props()
  let open = $state(false)
  let timer: ReturnType<typeof setTimeout> | undefined

  function onmouseenter() {
    timer = setTimeout(() => (open = true), openDelay)
  }
  function onmouseleave() {
    clearTimeout(timer)
    open = false
  }
</script>

<div class="relative inline-block" {onmouseenter} {onmouseleave}>
  <slot name="trigger" />
  {#if open}
    <div class={['absolute z-50 mt-1 w-64 rounded-md border bg-popover p-4 text-popover-foreground shadow-md outline-none', className].join(' ')} {...props}>
      <slot />
    </div>
  {/if}
</div>

// packages/ui-angular/src/lib/hover-card/hover-card.component.ts
import { Component, ChangeDetectionStrategy } from '@angular/core'
import { CommonModule } from '@angular/common'

@Component({
  selector: 'paul-hover-card',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="relative inline-block" (mouseenter)="open = true" (mouseleave)="open = false">
      <ng-content select="[slot=trigger]" />
      <div *ngIf="open" class="absolute start-0 top-full z-50 mt-2 w-64 rounded-md border bg-popover p-4 text-sm text-popover-foreground shadow-md animate-in fade-in-0 zoom-in-95">
        <ng-content />
      </div>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class HoverCardComponent {
  open = false
}
