// packages/ui-svelte/src/lib/components/ScrollArea.svelte
<script lang="ts">
  /**
   * ScrollArea — custom scrollable container with styled scrollbars.
   *
   * @example
   * ```svelte
   * <ScrollArea class="h-72 w-48 rounded-md border">
   *   {#each items as item}
   *     <div class="p-4">{item}</div>
   *   {/each}
   * </ScrollArea>
   * ```
   */
  import { cn } from '../utils'
  interface Props { class?: string; children?: import('svelte').Snippet }
  const { class: cls = '', children }: Props = $props()
</script>
<div class={cn('relative overflow-hidden', cls)}>
  <div class="h-full w-full overflow-auto scroll-py-1" tabindex="0">{@render children?.()}</div>
</div>

// packages/ui-angular/src/lib/scroll-area/scroll-area.component.ts
import { Component, Input, HostBinding, ChangeDetectionStrategy } from '@angular/core'
import { cn } from '../../lib/utils'

/**
 * ScrollArea — custom scrollable container with styled scrollbars.
 *
 * @example
 * ```html
 * <paul-scroll-area class="h-72 w-48 rounded-md border">
 *   <div *ngFor="let item of items" class="p-4">{{ item }}</div>
 * </paul-scroll-area>
 * ```
 */
@Component({
  selector: 'paul-scroll-area',
  standalone: true,
  template: `
    <div class="relative overflow-hidden h-full w-full">
      <div class="h-full w-full overflow-auto scroll-py-1" tabindex="0">
        <ng-content />
      </div>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ScrollAreaComponent {
  @Input() class = ''
  @HostBinding('class') get hostClass() { return cn('relative overflow-hidden', this.class) }
}
