// packages/ui-svelte/src/lib/components/Kbd.svelte
<script lang="ts">
  /**
   * Kbd — displays keyboard shortcut keys.
   *
   * @example
   * ```svelte
   * <span>Press <Kbd>⌘</Kbd> + <Kbd>K</Kbd></span>
   * ```
   */
  import { cn } from '../utils'
  interface Props { class?: string; children?: import('svelte').Snippet }
  const { class: cls = '', children }: Props = $props()
</script>
<kbd class={cn('pointer-events-none inline-flex h-5 select-none items-center gap-1 rounded border bg-muted px-1.5 font-mono text-[10px] font-medium text-muted-foreground opacity-100', cls)}>
  {@render children?.()}
</kbd>

// packages/ui-angular/src/lib/kbd/kbd.component.ts
import { Component, Input, HostBinding, ChangeDetectionStrategy } from '@angular/core'
import { cn } from '../../lib/utils'

/**
 * Kbd — displays keyboard shortcut keys.
 *
 * @example
 * ```html
 * <span>Press <paul-kbd>⌘</paul-kbd> + <paul-kbd>K</paul-kbd></span>
 * ```
 */
@Component({ selector: 'paul-kbd', standalone: true, template: `<ng-content />`, changeDetection: ChangeDetectionStrategy.OnPush })
export class KbdComponent {
  @Input() class = ''
  @HostBinding('class') get hostClass() {
    return cn('pointer-events-none inline-flex h-5 select-none items-center gap-1 rounded border bg-muted px-1.5 font-mono text-[10px] font-medium text-muted-foreground opacity-100', this.class)
  }
}
