// packages/ui-svelte/src/lib/components/Carousel.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  let { class: className = '', children, ...props }: { class?: string; children?: Snippet; [key: string]: unknown } = $props()
  let current = $state(0)
  let items: HTMLElement[] = $state([])

  function prev() { current = Math.max(0, current - 1) }
  function next() { current = Math.min(items.length - 1, current + 1) }
</script>

<div class={['relative overflow-hidden', className].join(' ')} {...props}>
  <div class="flex transition-transform duration-300" style={`transform: translateX(-${current * 100}%)`}>
    {@render children?.()}
  </div>
  <button onclick={prev} disabled={current === 0} aria-label="Previous slide" class="absolute start-2 top-1/2 -translate-y-1/2 z-10 h-8 w-8 rounded-full border bg-background shadow flex items-center justify-center disabled:opacity-50">
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m15 18-6-6 6-6"/></svg>
  </button>
  <button onclick={next} aria-label="Next slide" class="absolute end-2 top-1/2 -translate-y-1/2 z-10 h-8 w-8 rounded-full border bg-background shadow flex items-center justify-center disabled:opacity-50">
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m9 18 6-6-6-6"/></svg>
  </button>
</div>

// packages/ui-angular/src/lib/carousel/carousel.component.ts
import { Component, Input, ChangeDetectionStrategy } from '@angular/core'
import { CommonModule } from '@angular/common'

@Component({ selector: 'paul-carousel-item', standalone: true, template: `<div class="min-w-0 shrink-0 grow-0 basis-full ps-4"><ng-content /></div>`, changeDetection: ChangeDetectionStrategy.OnPush })
export class CarouselItemComponent {}

@Component({
  selector: 'paul-carousel',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="relative">
      <div class="overflow-hidden">
        <div class="flex -ms-4" [style.transform]="'translateX(-' + (current * 100) + '%)'">
          <ng-content />
        </div>
      </div>
      <button (click)="prev()" class="absolute start-2 top-1/2 -translate-y-1/2 flex h-8 w-8 items-center justify-center rounded-full border bg-background shadow hover:bg-accent" type="button" aria-label="Previous">‹</button>
      <button (click)="next()" class="absolute end-2 top-1/2 -translate-y-1/2 flex h-8 w-8 items-center justify-center rounded-full border bg-background shadow hover:bg-accent" type="button" aria-label="Next">›</button>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CarouselComponent {
  @Input() total = 3
  current = 0
  prev() { if (this.current > 0) this.current-- }
  next() { if (this.current < this.total - 1) this.current++ }
}
