// packages/ui-vue/src/components/pagination-next.vue
<script setup lang="ts">
import { cn } from '../lib/utils'
const props = defineProps<{ href?: string; class?: string }>()
</script>

<template>
  <a
    :href="props.href"
    aria-label="Go to next page"
    :class="cn('inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 hover:bg-accent hover:text-accent-foreground h-9 px-4 gap-1 pr-2.5', props.class)"
  >
    <span>Next</span>
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m9 18 6-6-6-6"/></svg>
  </a>
</template>

// packages/ui-angular/src/lib/pagination/pagination.component.ts
import { Component, Input, ChangeDetectionStrategy } from '@angular/core'
import { CommonModule } from '@angular/common'
import { cn } from '../../lib/utils'

@Component({ selector: 'paul-pagination', standalone: true, template: `<nav role="navigation" aria-label="pagination" class="mx-auto flex w-full justify-center"><ng-content /></nav>`, changeDetection: ChangeDetectionStrategy.OnPush })
export class PaginationComponent {}

@Component({ selector: 'paul-pagination-content', standalone: true, template: `<ul class="flex flex-row items-center gap-1"><ng-content /></ul>`, changeDetection: ChangeDetectionStrategy.OnPush })
export class PaginationContentComponent {}

@Component({ selector: 'paul-pagination-item', standalone: true, template: `<li><ng-content /></li>`, changeDetection: ChangeDetectionStrategy.OnPush })
export class PaginationItemComponent {}

@Component({
  selector: 'paul-pagination-link',
  standalone: true,
  imports: [CommonModule],
  template: `<a [attr.aria-current]="isActive ? 'page' : null" [class]="linkClass"><ng-content /></a>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PaginationLinkComponent {
  @Input() isActive = false
  @Input() class = ''
  get linkClass() {
    return cn('inline-flex items-center justify-center rounded-md border text-sm h-11 w-11 hover:bg-accent', this.isActive ? 'bg-primary text-primary-foreground hover:bg-primary/90 border-primary' : 'bg-background', this.class)
  }
}

@Component({ selector: 'paul-pagination-previous', standalone: true, template: `<a class="inline-flex h-11 items-center gap-1 px-3 text-sm rounded-md border hover:bg-accent"><span>«</span><span>Previous</span></a>`, changeDetection: ChangeDetectionStrategy.OnPush })
export class PaginationPreviousComponent {}

@Component({ selector: 'paul-pagination-next', standalone: true, template: `<a class="inline-flex h-11 items-center gap-1 px-3 text-sm rounded-md border hover:bg-accent"><span>Next</span><span>»</span></a>`, changeDetection: ChangeDetectionStrategy.OnPush })
export class PaginationNextComponent {}

@Component({ selector: 'paul-pagination-ellipsis', standalone: true, template: `<span aria-hidden="true" class="flex h-11 w-11 items-center justify-center"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/><circle cx="5" cy="12" r="1"/></svg><span class="sr-only">More pages</span></span>`, changeDetection: ChangeDetectionStrategy.OnPush })
export class PaginationEllipsisComponent {}
