// packages/ui/src/components/pagination.tsx
import * as React from 'react'
import { ChevronLeft, ChevronRight, MoreHorizontal } from 'lucide-react'
import { cn } from '@/lib/utils'
import { ButtonProps, buttonVariants } from './button'

const Pagination = ({ className, ...props }: React.ComponentProps<'nav'>) => (
  <nav
    role="navigation"
    aria-label="pagination"
    className={cn('mx-auto flex w-full justify-center', className)}
    {...props}
  />
)
Pagination.displayName = 'Pagination'

const PaginationContent = React.forwardRef<
  HTMLUListElement,
  React.ComponentProps<'ul'>
>(({ className, ...props }, ref) => (
  <ul
    ref={ref}
    className={cn('flex flex-row items-center gap-1', className)}
    {...props}
  />
))
PaginationContent.displayName = 'PaginationContent'

const PaginationItem = React.forwardRef<
  HTMLLIElement,
  React.ComponentProps<'li'>
>(({ className, ...props }, ref) => (
  <li ref={ref} className={cn('', className)} {...props} />
))
PaginationItem.displayName = 'PaginationItem'

type PaginationLinkProps = {
  isActive?: boolean
} & Pick<ButtonProps, 'size'> &
  React.ComponentProps<'a'>

const PaginationLink = ({
  className,
  isActive,
  size = 'icon',
  ...props
}: PaginationLinkProps) => (
  <a
    aria-current={isActive ? 'page' : undefined}
    className={cn(
      buttonVariants({
        variant: isActive ? 'outline' : 'ghost',
        size,
      }),
      className
    )}
    {...props}
  />
)
PaginationLink.displayName = 'PaginationLink'

const PaginationPrevious = ({
  className,
  ...props
}: React.ComponentProps<typeof PaginationLink>) => (
  <PaginationLink
    aria-label="Go to previous page"
    size="default"
    className={cn('gap-1 pl-2.5', className)}
    {...props}
  >
    <ChevronLeft className="h-4 w-4" />
    <span>Previous</span>
  </PaginationLink>
)
PaginationPrevious.displayName = 'PaginationPrevious'

const PaginationNext = ({
  className,
  ...props
}: React.ComponentProps<typeof PaginationLink>) => (
  <PaginationLink
    aria-label="Go to next page"
    size="default"
    className={cn('gap-1 pr-2.5', className)}
    {...props}
  >
    <span>Next</span>
    <ChevronRight className="h-4 w-4" />
  </PaginationLink>
)
PaginationNext.displayName = 'PaginationNext'

const PaginationEllipsis = ({
  className,
  ...props
}: React.ComponentProps<'span'>) => (
  <span
    aria-hidden
    className={cn('flex h-9 w-9 items-center justify-center', className)}
    {...props}
  >
    <MoreHorizontal className="h-4 w-4" />
    <span className="sr-only">More pages</span>
  </span>
)
PaginationEllipsis.displayName = 'PaginationEllipsis'

export {
  Pagination,
  PaginationContent,
  PaginationEllipsis,
  PaginationItem,
  PaginationLink,
  PaginationNext,
  PaginationPrevious,
}

// packages/ui-angular/src/lib/pagination/pagination.component.ts
import { Component, Input, ChangeDetectionStrategy, HostBinding } from '@angular/core'
import { CommonModule } from '@angular/common'
import { cn } from '../../lib/utils'

@Component({ selector: 'paul-pagination', standalone: true, template: `<nav role="navigation" aria-label="pagination" class="mx-auto flex w-full justify-center"><ng-content /></nav>`, changeDetection: ChangeDetectionStrategy.OnPush })
export class PaginationComponent {}

@Component({ selector: 'paul-pagination-content', standalone: true, template: `<ul class="flex flex-row items-center gap-1"><ng-content /></ul>`, changeDetection: ChangeDetectionStrategy.OnPush })
export class PaginationContentComponent {}

@Component({ selector: 'paul-pagination-item', standalone: true, template: `<li><ng-content /></li>`, changeDetection: ChangeDetectionStrategy.OnPush })
export class PaginationItemComponent {}

@Component({
  selector: 'paul-pagination-link',
  standalone: true,
  imports: [CommonModule],
  template: `<a [attr.aria-current]="isActive ? 'page' : null" [class]="linkClass"><ng-content /></a>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PaginationLinkComponent {
  @Input() isActive = false
  @Input() class = ''
  get linkClass() {
    return cn('inline-flex items-center justify-center rounded-md border text-sm h-9 w-9 hover:bg-accent', this.isActive ? 'bg-primary text-primary-foreground hover:bg-primary/90 border-primary' : 'bg-background', this.class)
  }
}

@Component({ selector: 'paul-pagination-previous', standalone: true, template: `<a class="inline-flex h-9 items-center gap-1 px-3 text-sm rounded-md border hover:bg-accent"><span>«</span><span>Previous</span></a>`, changeDetection: ChangeDetectionStrategy.OnPush })
export class PaginationPreviousComponent {}

@Component({ selector: 'paul-pagination-next', standalone: true, template: `<a class="inline-flex h-9 items-center gap-1 px-3 text-sm rounded-md border hover:bg-accent"><span>Next</span><span>»</span></a>`, changeDetection: ChangeDetectionStrategy.OnPush })
export class PaginationNextComponent {}

@Component({ selector: 'paul-pagination-ellipsis', standalone: true, template: `<span aria-hidden="true" class="flex h-9 w-9 items-center justify-center">…</span>`, changeDetection: ChangeDetectionStrategy.OnPush })
export class PaginationEllipsisComponent {}
