// packages/ui-angular/src/lib/accordion/accordion-item.component.ts
import { Component, Input, HostBinding, ChangeDetectionStrategy } from '@angular/core'
import { CommonModule } from '@angular/common'

/** A single accordion section. Requires a unique `value` prop. */
@Component({
  selector: 'paul-accordion-item',
  standalone: true,
  imports: [CommonModule],
  template: `<ng-content />`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AccordionItemComponent {
  @Input() value!: string
  @HostBinding('class') get hostClass() { return 'block border-b' }
  open = false
}

// packages/ui-svelte/src/lib/components/AccordionItem.svelte
<script lang="ts">
  /** A single accordion section. Requires a unique `value` prop. */
  import { getContext } from 'svelte'
  import { melt } from '@melt-ui/svelte'

  interface Props {
    value: string
    class?: string
    children?: import('svelte').Snippet
  }
  const { value, class: cls = '', children }: Props = $props()
  const accordion = getContext<any>('paul-accordion')
</script>
<div use:melt={accordion.elements.item(value)} class={['border-b', cls].filter(Boolean).join(' ')}>
  {@render children?.()}
</div>
