// packages/ui-vue/src/components/accordion.vue
<script setup lang="ts">
import {
  AccordionRoot,
  type AccordionRootProps,
} from 'radix-vue'
import { cn } from '@/lib/utils'

/**
 * Accordion — root container. Set `type="single"` for one-open or `type="multiple"` for multi-open.
 *
 * @example
 * ```vue
 * <Accordion type="single" collapsible>
 *   <AccordionItem value="item-1">
 *     <AccordionTrigger>Is it accessible?</AccordionTrigger>
 *     <AccordionContent>Yes. It adheres to WAI-ARIA.</AccordionContent>
 *   </AccordionItem>
 * </Accordion>
 * ```
 *
 * @accessibility Built on Radix Vue AccordionRoot. Keyboard-navigable with Arrow keys.
 */
defineOptions({ name: 'Accordion' })
const props = defineProps<{
  as?: string | any
  class?: string
}>()
const tag = props.as || AccordionRoot
</script>

<template>
  <component :is="tag" v-bind="props" :class="cn(props.class)">
    <slot />
  </component>
</template>

// packages/ui-svelte/src/lib/components/Accordion.svelte
<script lang="ts">
  // Accordion -- root container backed by Melt UI.
  // Set type="single" (default) or type="multiple".
  //
  // @example
  //   <Accordion type="single">
  //     <AccordionItem value="item-1">
  //       <AccordionTrigger>Is it accessible?</AccordionTrigger>
  //       <AccordionContent>Yes. Built on Melt UI.</AccordionContent>
  //     </AccordionItem>
  //   </Accordion>
  //
  // @accessibility Keyboard-navigable with Arrow keys. ARIA expanded/controls wired automatically.
  import { createAccordion, melt } from '@melt-ui/svelte'
  import { setContext } from 'svelte'

  interface Props {
    type?: 'single' | 'multiple'
    collapsible?: boolean
    value?: string | string[]
    class?: string
    children?: import('svelte').Snippet
  }
  const { type = 'single', collapsible = false, value, class: cls = '', children }: Props = $props()

  const accordion = createAccordion({ type: 'single', forceVisible: false })
  setContext('paul-accordion', accordion)
</script>
<div use:melt={accordion.elements.root} class={cls}>
  {@render children?.()}
</div>
