// packages/ui-angular/src/lib/accordion/accordion-content.component.ts
import { Component, Input, ChangeDetectionStrategy } from '@angular/core'
import { CommonModule } from '@angular/common'

/** Collapsible content panel rendered below AccordionTrigger. */
@Component({
  selector: 'paul-accordion-content',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div *ngIf="open" class="overflow-hidden text-sm">
      <div class="pb-4 pt-0">
        <ng-content />
      </div>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AccordionContentComponent {
  @Input() open = false
}

// packages/ui-svelte/src/lib/components/AccordionContent.svelte
<script lang="ts">
  /** Collapsible content panel rendered below AccordionTrigger. */
  import { getContext } from 'svelte'
  import { melt } from '@melt-ui/svelte'
  import { cn } from '../utils'

  interface Props {
    value: string
    class?: string
    children?: import('svelte').Snippet
  }
  const { value, class: cls = '', children }: Props = $props()
  const accordion = getContext<any>('paul-accordion')
</script>
<div use:melt={accordion.elements.content(value)} class={cn('overflow-hidden text-sm', cls)}>
  <div class="pb-4 pt-0">{@render children?.()}</div>
</div>
