// packages/ui-vue/src/components/alert-title.vue
<script setup lang="ts">
import { cn } from '@/lib/utils'
/** Primary heading inside an Alert. */
defineOptions({ name: 'AlertTitle' })
const props = defineProps<{ class?: string }>()
</script>
<template><h5 :class="cn('mb-1 font-medium leading-none tracking-tight', props.class)"><slot /></h5></template>

// packages/ui-svelte/src/lib/components/AlertTitle.svelte
<script lang="ts">
  /** Primary heading inside an Alert. */
  import { cn } from '../utils'
  interface Props { class?: string; children?: import('svelte').Snippet }
  const { class: cls = '', children }: Props = $props()
</script>
<h5 class={cn('mb-1 font-medium leading-none tracking-tight', cls)}>{@render children?.()}</h5>
