// packages/ui-vue/src/components/alert-description.vue
<script setup lang="ts">
import { cn } from '@/lib/utils'
/** Supporting description text inside an Alert. */
defineOptions({ name: 'AlertDescription' })
const props = defineProps<{ class?: string }>()
</script>
<template><div :class="cn('text-sm [&_p]:leading-relaxed', props.class)"><slot /></div></template>

// packages/ui-svelte/src/lib/components/AlertDescription.svelte
<script lang="ts">
  /** Supporting description text inside an Alert. */
  import { cn } from '../utils'
  interface Props { class?: string; children?: import('svelte').Snippet }
  const { class: cls = '', children }: Props = $props()
</script>
<div class={cn('text-sm [&_p]:leading-relaxed', cls)}>{@render children?.()}</div>
