// packages/ui-vue/src/components/avatar-fallback.vue
<script setup lang="ts">
import { AvatarFallback, type AvatarFallbackProps } from 'radix-vue'
import { cn } from '@/lib/utils'

/** Fallback initials or icon shown when the AvatarImage cannot load. */
defineOptions({ name: 'AvatarFallback' })
const props = defineProps<{ class?: string }>()
</script>

<template>
  <AvatarFallback v-bind="props" :class="cn('flex h-full w-full items-center justify-center rounded-full bg-muted', props.class)" />
</template>

// packages/ui-svelte/src/lib/components/AvatarFallback.svelte
<script lang="ts">
  /** Fallback initials or icon shown when AvatarImage cannot load. */
  import { cn } from '../utils'
  interface Props { class?: string; children?: import('svelte').Snippet }
  const { class: cls = '', children }: Props = $props()
</script>
<span class={cn('flex h-full w-full items-center justify-center rounded-full bg-muted text-sm font-medium', cls)}>
  {@render children?.()}
</span>
