// packages/ui-vue/src/components/breadcrumb-separator.vue
<script setup lang="ts">
import { cn } from '../lib/utils'
const props = defineProps<{ class?: string }>()
</script>

<template>
  <li role="presentation" aria-hidden="true" :class="cn('[&>svg]:size-3.5', props.class)">
    <slot>
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m9 18 6-6-6-6"/></svg>
    </slot>
  </li>
</template>

// packages/ui-svelte/src/lib/components/BreadcrumbSeparator.svelte
<script lang="ts">
  let { class: className = '', ...props } = $props()
</script>
<li role="presentation" aria-hidden="true" class={['[&>svg]:size-3.5', className].join(' ')} {...props}>
  <slot><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m9 18 6-6-6-6"/></svg></slot>
</li>
