// packages/ui-vue/src/components/button-group.vue
<script setup lang="ts">
import { cn } from '@/lib/utils'
/**
 * ButtonGroup — renders a horizontal group of buttons with no gap and merged borders.
 *
 * @example
 * ```vue
 * <ButtonGroup>
 *   <Button variant="outline">Left</Button>
 *   <Button variant="outline">Middle</Button>
 *   <Button variant="outline">Right</Button>
 * </ButtonGroup>
 * ```
 */
defineOptions({ name: 'ButtonGroup' })
const props = defineProps<{ class?: string }>()
</script>

<template>
  <div :class="cn('flex [&>*:not(:first-child)]:-ms-px [&>*:not(:first-child)]:rounded-s-none [&>*:not(:last-child)]:rounded-e-none', props.class)">
    <slot />
  </div>
</template>

// packages/ui-svelte/src/lib/components/ButtonGroup.svelte
<script lang="ts">
  /**
   * ButtonGroup — horizontal group of buttons with merged borders.
   *
   * @example
   * ```svelte
   * <ButtonGroup>
   *   <Button variant="outline">Left</Button>
   *   <Button variant="outline">Middle</Button>
   *   <Button variant="outline">Right</Button>
   * </ButtonGroup>
   * ```
   */
  import { cn } from '../utils'
  interface Props { class?: string; children?: import('svelte').Snippet }
  const { class: cls = '', children }: Props = $props()
</script>
<div class={cn('flex [&>*:not(:first-child)]:-ml-px [&>*:not(:first-child)]:rounded-l-none [&>*:not(:last-child)]:rounded-r-none', cls)}>
  {@render children?.()}
</div>
