// packages/ui-vue/src/components/card-description.vue
<script setup lang="ts">
import { cn } from '@/lib/utils'
/** Secondary supporting text inside CardHeader. */
defineOptions({ name: 'CardDescription' })
const props = defineProps<{ class?: string }>()
</script>
<template><div :class="cn('text-sm text-muted-foreground', props.class)"><slot /></div></template>

// packages/ui-svelte/src/lib/components/CardDescription.svelte
<script lang="ts">
  /** Secondary supporting text inside CardHeader. */
  import { cn } from '../utils'
  interface Props { class?: string; children?: import('svelte').Snippet }
  const { class: cls = '', children }: Props = $props()
</script>
<p class={cn('text-sm text-muted-foreground', cls)}>{@render children?.()}</p>
