// packages/ui-vue/src/components/card-title.vue
<script setup lang="ts">
import { cn } from '@/lib/utils'
/** Primary heading inside CardHeader. */
defineOptions({ name: 'CardTitle' })
const props = defineProps<{ class?: string }>()
</script>
<template><div :class="cn('font-semibold leading-none tracking-tight', props.class)"><slot /></div></template>

// packages/ui-svelte/src/lib/components/CardTitle.svelte
<script lang="ts">
  /** Primary heading inside CardHeader. */
  import { cn } from '../utils'
  interface Props { class?: string; children?: import('svelte').Snippet }
  const { class: cls = '', children }: Props = $props()
</script>
<h3 class={cn('font-semibold leading-none tracking-tight', cls)}>{@render children?.()}</h3>
