// packages/ui-vue/src/components/command-group.vue
<script setup lang="ts">
import { cn } from '../lib/utils'
const props = defineProps<{ heading?: string; class?: string }>()
</script>
<template>
  <div :class="cn('overflow-hidden p-1 text-foreground', props.class)">
    <div v-if="props.heading" class="px-2 py-1.5 text-xs font-medium text-muted-foreground">{{ props.heading }}</div>
    <slot />
  </div>
</template>

// packages/ui-svelte/src/lib/components/CommandGroup.svelte
<script lang="ts">
  let { heading = '', class: className = '', ...props } = $props()
</script>
<div class={['overflow-hidden p-1 text-foreground', className].join(' ')} {...props}>
  {#if heading}
    <div class="px-2 py-1.5 text-xs font-medium text-muted-foreground">{heading}</div>
  {/if}
  <slot />
</div>
