// packages/ui-angular/src/lib/dialog/dialog-description.component.ts
import { Component, Input, HostBinding, ChangeDetectionStrategy } from '@angular/core'
import { cn } from '../../lib/utils'

/** Supporting description text rendered below DialogTitle. */
@Component({ selector: 'paul-dialog-description', standalone: true, template: `<ng-content />`, changeDetection: ChangeDetectionStrategy.OnPush })
export class DialogDescriptionComponent {
  @Input() class = ''
  @HostBinding('class') get hostClass() { return cn('text-sm text-muted-foreground', this.class) }
}

// packages/ui-svelte/src/lib/components/DialogDescription.svelte
<script lang="ts">
  /** Supporting description rendered below DialogTitle. */
  import { getContext } from 'svelte'
  import { melt } from '@melt-ui/svelte'
  import { cn } from '../utils'
  interface Props { class?: string; children?: import('svelte').Snippet }
  const { class: cls = '', children }: Props = $props()
  const dialog = getContext<ReturnType<typeof import('@melt-ui/svelte').createDialog>>('paul-dialog')
</script>
<p use:melt={dialog.elements.description} class={cn('text-sm text-muted-foreground', cls)}>{@render children?.()}</p>
