// packages/ui-vue/src/components/dialog-header.vue
<script setup lang="ts">
import { cn } from '@/lib/utils'
/** Top section of DialogContent, containing DialogTitle and DialogDescription. */
defineOptions({ name: 'DialogHeader' })
const props = defineProps<{ class?: string }>()
</script>
<template><div :class="cn('flex flex-col space-y-1.5 text-center sm:text-left', props.class)"><slot /></div></template>

// packages/ui-svelte/src/lib/components/DialogHeader.svelte
<script lang="ts">
  /** Layout wrapper for the dialog title and description at the top. */
  import { cn } from '../utils'
  interface Props { class?: string; children?: import('svelte').Snippet }
  const { class: cls = '', children }: Props = $props()
</script>
<div class={cn('flex flex-col space-y-1.5 text-center sm:text-left', cls)}>{@render children?.()}</div>
