// packages/ui-angular/src/lib/dialog/dialog-footer.component.ts
import { Component, Input, HostBinding, ChangeDetectionStrategy } from '@angular/core'
import { cn } from '../../lib/utils'

/** Layout wrapper for action buttons at the bottom of the dialog. */
@Component({ selector: 'paul-dialog-footer', standalone: true, template: `<ng-content />`, changeDetection: ChangeDetectionStrategy.OnPush })
export class DialogFooterComponent {
  @Input() class = ''
  @HostBinding('class') get hostClass() { return cn('flex flex-col-reverse sm:flex-row sm:justify-end sm:space-x-2', this.class) }
}

// packages/ui-svelte/src/lib/components/DialogFooter.svelte
<script lang="ts">
  /** Layout wrapper for action buttons at the bottom of the dialog. */
  import { cn } from '../utils'
  interface Props { class?: string; children?: import('svelte').Snippet }
  const { class: cls = '', children }: Props = $props()
</script>
<div class={cn('flex flex-col-reverse sm:flex-row sm:justify-end sm:space-x-2', cls)}>{@render children?.()}</div>
