// packages/ui-vue/src/components/dialog-footer.vue
<script setup lang="ts">
import { cn } from '@/lib/utils'
/** Bottom section of DialogContent, typically containing action buttons. */
defineOptions({ name: 'DialogFooter' })
const props = defineProps<{ class?: string }>()
</script>
<template><div :class="cn('flex flex-col-reverse sm:flex-row sm:justify-end sm:space-x-2', props.class)"><slot /></div></template>

// packages/ui-svelte/src/lib/components/DialogFooter.svelte
<script lang="ts">
  /** Layout wrapper for action buttons at the bottom of the dialog. */
  import { cn } from '../utils'
  interface Props { class?: string; children?: import('svelte').Snippet }
  const { class: cls = '', children }: Props = $props()
</script>
<div class={cn('flex flex-col-reverse sm:flex-row sm:justify-end sm:space-x-2', cls)}>{@render children?.()}</div>
