// packages/ui-vue/src/components/input-group.vue
<script setup lang="ts">
import { cn } from '@/lib/utils'
/**
 * InputGroup — combines an input with prefix/suffix addons, merging their borders.
 *
 * @example
 * ```vue
 * <InputGroup>
 *   <InputGroupText>https://</InputGroupText>
 *   <Input placeholder="example.com" />
 * </InputGroup>
 * ```
 */
defineOptions({ name: 'InputGroup' })
const props = defineProps<{ class?: string }>()
</script>
<template><div :class="cn('flex [&>*:not(:first-child)]:-ml-px [&>*:not(:last-child)]:rounded-r-none [&>*:not(:first-child)]:rounded-l-none', props.class)"><slot /></div></template>

// packages/ui-svelte/src/lib/components/InputGroup.svelte
<script lang="ts">
  /**
   * InputGroup — combines an input with prefix/suffix addons.
   *
   * @example
   * ```svelte
   * <InputGroup>
   *   <InputGroupText>https://</InputGroupText>
   *   <Input placeholder="example.com" />
   * </InputGroup>
   * ```
   */
  import { cn } from '../utils'
  interface Props { class?: string; children?: import('svelte').Snippet }
  const { class: cls = '', children }: Props = $props()
</script>
<div class={cn('flex [&>input]:rounded-none [&>input:first-child]:rounded-s-md [&>input:last-child]:rounded-e-md', cls)}>
  {@render children?.()}
</div>
