// packages/ui-vue/src/components/input-otp.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import { cn } from '../lib/utils'

const props = defineProps<{ maxLength?: number; class?: string }>()
const emit = defineEmits<{ (e: 'update:modelValue', v: string): void }>()
const modelValue = defineModel<string>({ default: '' })
const maxLen = computed(() => props.maxLength ?? 6)

function onInput(e: Event) {
  const val = (e.target as HTMLInputElement).value.replace(/\D/g, '').slice(0, maxLen.value)
  modelValue.value = val
}
</script>
<template>
  <div :class="cn('flex items-center gap-2', props.class)" role="group" :aria-label="'One-time password'">
    <input
      type="text"
      inputmode="numeric"
      autocomplete="one-time-code"
      :maxlength="maxLen"
      :value="modelValue"
      @input="onInput"
      class="sr-only"
      :aria-label="'Enter one-time password, ' + maxLen + ' digits'"
    />
    <div class="flex items-center">
      <div
        v-for="i in maxLen"
        :key="i"
        :class="cn(
          'relative flex h-11 w-11 items-center justify-center border-y border-r border-input text-sm transition-all first:rounded-l-md first:border-l last:rounded-r-md',
        )"
      >
        {{ modelValue[i - 1] ?? '' }}
        <div v-if="!modelValue[i - 1]" class="pointer-events-none absolute inset-0 flex items-center justify-center">
          <div class="h-4 w-px bg-foreground opacity-50" />
        </div>
      </div>
    </div>
  </div>
</template>

// packages/ui-svelte/src/lib/components/InputOTP.svelte
<script lang="ts">
  let { value = $bindable(''), maxLength = 6, class: className = '', ...props } = $props()

  let slots = $derived(Array.from({ length: maxLength }, (_, i) => value[i] ?? ''))
  let inputEl: HTMLInputElement

  function oninput(e: Event) {
    const v = (e.target as HTMLInputElement).value.replace(/\D/g, '').slice(0, maxLength)
    value = v
  }
</script>

<div class={['relative flex items-center gap-2', className].join(' ')} {...props} onclick={() => inputEl?.focus()}>
  <input
    bind:this={inputEl}
    type="text"
    inputmode="numeric"
    autocomplete="one-time-code"
    maxlength={maxLength}
    value={value}
    {oninput}
    aria-label={'Enter one-time password, ' + maxLength + ' digits'}
    class="sr-only"
  />
  {#each slots as slot, i}
    <div
      class={['relative flex h-11 w-11 items-center justify-center border-y border-r border-input text-sm transition-all first:rounded-l-md first:border-l last:rounded-r-md', i === value.length ? 'ring-2 ring-ring ring-offset-background z-10' : ''].join(' ')}
      aria-hidden="true"
    >
      {slot}
      {#if i === value.length}
        <div class="pointer-events-none absolute inset-0 flex items-center justify-center">
          <div class="animate-caret-blink h-4 w-px bg-foreground duration-1000"></div>
        </div>
      {/if}
    </div>
  {/each}
</div>
