// packages/ui-vue/src/components/menubar-trigger.vue
<script setup lang="ts">
import { MenubarTrigger } from 'radix-vue'
import { cn } from '@/lib/utils'
/** Button in the Menubar that opens a dropdown MenubarContent on click. */
defineOptions({ name: 'MenubarTrigger' })
const props = defineProps<{ class?: string }>()
</script>
<template><MenubarTrigger :class="cn('flex cursor-default select-none items-center rounded-sm px-3 py-1 text-sm font-medium outline-none focus:bg-accent focus:text-accent-foreground data-[state=open]:bg-accent data-[state=open]:text-accent-foreground', props.class)"><slot /></MenubarTrigger></template>

// packages/ui-svelte/src/lib/components/MenubarTrigger.svelte
<script lang="ts">
  let { class: className = '', onclick, ...props } = $props()
</script>
<button {onclick} class={['flex cursor-default select-none items-center rounded-sm px-3 py-1.5 text-sm font-medium outline-none hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground', className].join(' ')} {...props}><slot /></button>
