// packages/ui-vue/src/components/navigation-menu-link.vue
<script setup lang="ts">
import { cn } from '../lib/utils'
const props = defineProps<{ href?: string; class?: string }>()
</script>
<template>
  <a :href="props.href" :class="cn('block select-none space-y-1 rounded-md p-3 leading-none no-underline outline-none transition-colors hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground', props.class)">
    <slot />
  </a>
</template>

// packages/ui-svelte/src/lib/components/NavigationMenuLink.svelte
<script lang="ts">
  let { href = '#', class: className = '', ...props } = $props()
</script>
<a {href} class={['group inline-flex h-10 w-max items-center justify-center rounded-md bg-background px-4 py-2 text-sm font-medium transition-colors hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground focus:outline-none disabled:pointer-events-none disabled:opacity-50', className].join(' ')} {...props}><slot /></a>
