// packages/ui-vue/src/components/pagination-link.vue
<script setup lang="ts">
import { cn } from '../lib/utils'
const props = defineProps<{ href?: string; isActive?: boolean; class?: string }>()
</script>

<template>
  <a
    :href="props.href"
    :aria-current="props.isActive ? 'page' : undefined"
    :class="cn(
      'inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 h-11 w-11',
      props.isActive ? 'border border-input bg-background hover:bg-accent hover:text-accent-foreground' : 'hover:bg-accent hover:text-accent-foreground',
      props.class
    )"
  >
    <slot />
  </a>
</template>

// packages/ui-svelte/src/lib/components/PaginationLink.svelte
<script lang="ts">
  let { href = '#', isActive = false, class: className = '', ...props } = $props()
</script>
<a {href} aria-current={isActive ? 'page' : undefined} class={['inline-flex items-center justify-center rounded-md text-sm font-medium h-10 w-10', isActive ? 'border bg-background shadow-sm' : 'hover:bg-accent hover:text-accent-foreground', className].join(' ')} {...props}><slot /></a>
