// packages/ui-vue/src/components/pagination-ellipsis.vue
<script setup lang="ts">
import { cn } from '../lib/utils'
const props = defineProps<{ class?: string }>()
</script>

<template>
  <span aria-hidden="true" :class="cn('flex h-9 w-9 items-center justify-center', props.class)">
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/><circle cx="5" cy="12" r="1"/></svg>
    <span class="sr-only">More pages</span>
  </span>
</template>

// packages/ui-svelte/src/lib/components/PaginationEllipsis.svelte
<script lang="ts">
  let { class: className = '', ...props } = $props()
</script>
<span aria-hidden="true" class={['flex h-9 w-9 items-center justify-center', className].join(' ')} {...props}>
  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/><circle cx="5" cy="12" r="1"/></svg>
  <span class="sr-only">More pages</span>
</span>
