// packages/ui-vue/src/components/separator.vue
<script setup lang="ts">
import { Separator as SeparatorRoot } from 'radix-vue'
import { cn } from '@/lib/utils'
/**
 * Separator — a visual or semantic divider between content sections.
 *
 * @example
 * ```vue
 * <Separator />
 * <Separator orientation="vertical" class="h-6" />
 * ```
 *
 * @accessibility Renders as `role="separator"` or `role="none"` based on the `decorative` prop.
 */
defineOptions({ name: 'Separator' })
const props = defineProps<{ orientation?: 'horizontal' | 'vertical'; decorative?: boolean; class?: string }>()
</script>
<template><SeparatorRoot v-bind="props" :class="cn('shrink-0 bg-border', props.orientation === 'vertical' ? 'h-full w-[1px]' : 'h-[1px] w-full', props.class)" /></template>

// packages/ui-svelte/src/lib/components/Separator.svelte
<script lang="ts">
  /**
   * Separator — a visual divider between content sections backed by Melt UI.
   *
   * @example
   * ```svelte
   * <Separator />
   * <Separator orientation="vertical" class="h-6" />
   * ```
   *
   * @accessibility Renders role="separator" or role="none" based on the decorative prop.
   */
  import { createSeparator, melt } from '@melt-ui/svelte'
  import { cn } from '../utils'

  interface Props { orientation?: 'horizontal' | 'vertical'; decorative?: boolean; class?: string }
  const { orientation = 'horizontal', decorative = true, class: cls = '' }: Props = $props()

  const { elements: { root } } = createSeparator({ orientation: 'horizontal', decorative: true })
</script>
<div
  use:melt={root}
  class={cn(
    'shrink-0 bg-border',
    orientation === 'horizontal' ? 'h-[1px] w-full' : 'h-full w-[1px]',
    cls
  )}
></div>
