// packages/ui-vue/src/components/sidebar.vue
<script setup lang="ts">
import { inject, Ref } from 'vue'
import { cn } from '../lib/utils'
const open = inject<Ref<boolean>>('sidebar-open')!
const props = defineProps<{ class?: string }>()
</script>
<template>
  <aside v-show="open" :class="cn('flex h-full w-64 flex-col border-e bg-sidebar text-sidebar-foreground', props.class)">
    <slot />
  </aside>
</template>

// packages/ui-svelte/src/lib/components/Sidebar.svelte
<script lang="ts">
  let { open = $bindable(true), side = 'left', class: className = '', ...props } = $props()
</script>

<div class="flex h-full">
  {#if open}
    <div class={['flex h-full w-[--sidebar-width,16rem] flex-col border-r bg-sidebar text-sidebar-foreground', side === 'right' ? 'order-last border-l border-r-0' : '', className].join(' ')} {...props}>
      <slot />
    </div>
  {/if}
  <div class="flex-1 overflow-auto">
    <slot name="content" />
  </div>
</div>
