// packages/ui-angular/src/lib/sonner/sonner.component.ts
import { Component, ChangeDetectionStrategy } from '@angular/core'
import { CommonModule } from '@angular/common'

interface ToastItem { id: number; message: string }

@Component({
  selector: 'paul-sonner',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="fixed bottom-4 right-4 z-[100] flex flex-col gap-2 w-80">
      <div *ngFor="let t of toasts" class="flex items-center justify-between rounded-md border bg-background px-4 py-3 shadow-lg text-sm">
        <span>{{ t.message }}</span>
        <button (click)="dismiss(t.id)" class="ml-4 text-muted-foreground hover:text-foreground">✕</button>
      </div>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SonnerComponent {
  toasts: ToastItem[] = []
  private nextId = 0

  toast(message: string) {
    const id = ++this.nextId
    this.toasts = [...this.toasts, { id, message }]
    setTimeout(() => this.dismiss(id), 4000)
  }

  dismiss(id: number) {
    this.toasts = this.toasts.filter(t => t.id !== id)
  }
}

// packages/ui-svelte/src/lib/components/Sonner.svelte
<script lang="ts">
  interface ToastItem { id: number; message: string; type?: string }
  let { class: className = '', ...props } = $props()
  let toasts = $state<ToastItem[]>([])
  let nextId = 0

  export function toast(message: string, type = 'default') {
    const id = nextId++
    toasts = [...toasts, { id, message, type }]
    setTimeout(() => { toasts = toasts.filter(t => t.id !== id) }, 4000)
  }
</script>

<div class={['fixed bottom-0 right-0 z-50 flex flex-col gap-2 p-4 pointer-events-none', className].join(' ')} {...props}>
  {#each toasts as t (t.id)}
    <div class={['pointer-events-auto flex items-center gap-3 rounded-md border bg-background px-4 py-3 shadow-lg text-sm', t.type === 'destructive' ? 'border-destructive text-destructive' : ''].join(' ')}>
      {t.message}
    </div>
  {/each}
</div>
