// packages/ui-vue/src/components/table.vue
<script setup lang="ts">
import { cn } from '../lib/utils'
const props = defineProps<{ class?: string }>()
</script>

<template>
  <div class="relative w-full overflow-auto">
    <table :class="cn('w-full caption-bottom text-sm print:border-black', props.class)">
      <slot />
    </table>
  </div>
</template>

// packages/ui-svelte/src/lib/components/Table.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  let { class: className = '', children, ...props} = $props()
</script>
<div class="relative w-full overflow-auto">
  <table class={['w-full caption-bottom text-sm print:border-black', className].join(' ')} {...props}>{@render children?.()}</table>
</div>
