// packages/ui-vue/src/components/table-head.vue
<script setup lang="ts">
import { cn } from '../lib/utils'
const props = defineProps<{
  as?: string | any
  class?: string
}>()
const tag = props.as || 'th'
</script>

<template>
  <component :is="tag" :class="cn('h-10 px-2 text-start align-middle font-medium text-muted-foreground', props.class)"><slot /></component>
</template>

// packages/ui-svelte/src/lib/components/TableHead.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  let { class: className = '', children, ...props} = $props()
</script>
<th class={['h-12 px-4 text-start align-middle font-medium text-muted-foreground [&:has([role=checkbox])]:pe-0', className].join(' ')} {...props}>{@render children?.()}</th>
