// packages/ui-vue/src/components/tabs-content.vue
<script setup lang="ts">
import { TabsContent, type TabsContentProps } from 'radix-vue'
import { cn } from '@/lib/utils'
/** Content panel shown when its matching TabsTrigger is active. Requires a `value` prop. */
defineOptions({ name: 'TabsContent' })
const props = defineProps<{ value: string; class?: string; forceMount?: boolean }>()
</script>
<template><TabsContent v-bind="props" :class="cn('mt-2 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring', props.class)"><slot /></TabsContent></template>

// packages/ui-svelte/src/lib/components/TabsContent.svelte
<script lang="ts">
  /** Content panel shown when its matching tab is active. Requires a value prop. */
  import { getContext } from 'svelte'
  import { melt } from '@melt-ui/svelte'
  import { cn } from '../utils'
  interface Props { value: string; class?: string; children?: import('svelte').Snippet }
  const { value, class: cls = '', children }: Props = $props()
  const tabs = getContext<ReturnType<typeof import('@melt-ui/svelte').createTabs>>('paul-tabs')
</script>
<div use:melt={tabs.elements.content(value)} class={cn('mt-2 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring', cls)}>
  {@render children?.()}
</div>
