// packages/ui-vue/src/components/tooltip.vue
<script setup lang="ts">
import { TooltipProvider, TooltipRoot, TooltipTrigger, TooltipPortal, TooltipContent, type TooltipContentProps } from 'radix-vue'
import { cn } from '@/lib/utils'
/**
 * Tooltip — concise text label that appears on hover/focus to describe an element.
 *
 * @example
 * ```vue
 * <Tooltip content="Save changes">
 *   <Button size="icon"><Save class="h-4 w-4" /></Button>
 * </Tooltip>
 * ```
 *
 * @accessibility The `content` prop becomes the tooltip text. For icon-only triggers also add `aria-label`.
 */
defineOptions({ name: 'Tooltip' })
const props = defineProps<{ content: string; class?: string }>()
</script>
<template>
  <TooltipProvider>
    <TooltipRoot>
      <TooltipTrigger as-child><slot /></TooltipTrigger>
      <TooltipPortal>
        <TooltipContent v-bind="props" :class="cn('z-50 overflow-hidden rounded-md bg-primary px-3 py-1.5 text-xs text-primary-foreground animate-in fade-in-0 zoom-in-95 data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=closed]:zoom-out-95 print:hidden', props.class)">{{ props.content }}</TooltipContent>
      </TooltipPortal>
    </TooltipRoot>
  </TooltipProvider>
</template>

// packages/ui-svelte/src/lib/components/Tooltip.svelte
<script lang="ts">
  // @ts-nocheck
  /**
   * Tooltip — concise text label on hover/focus backed by Melt UI.
   *
   * @example
   * ```svelte
   * <Tooltip content="Save changes">
   *   <Button size="icon" aria-label="Save">
   *     <SaveIcon />
   *   </Button>
   * </Tooltip>
   * ```
   *
   * @accessibility Content becomes tooltip text. For icon-only triggers also add aria-label.
   */
  import { createTooltip, melt } from '@melt-ui/svelte'
  import { cn } from '../utils'

  interface Props { content: string; class?: string; children?: import('svelte').Snippet }
  const { content, class: cls = '', children }: Props = $props()

  const { elements: { trigger, content: tooltipContent, arrow }, states: { open } } = createTooltip({ positioning: { placement: 'top' }, openDelay: 300 })
</script>
<span use:melt={trigger}>{@render children?.()}</span>
{#if $open}
  <div use:melt={tooltipContent} class={cn('z-50 overflow-hidden rounded-md bg-primary px-3 py-1.5 text-xs text-primary-foreground animate-in fade-in-0 zoom-in-95 print:hidden', cls)}>
    {content}
    <div use:melt={arrow}></div>
  </div>
{/if}
