// packages/ui-svelte/src/lib/components/AvatarFallback.svelte
<script lang="ts">
  /** Fallback initials or icon shown when AvatarImage cannot load. */
  import { cn } from '../utils'
  interface Props { class?: string; children?: import('svelte').Snippet }
  const { class: cls = '', children }: Props = $props()
</script>
<span class={cn('flex h-full w-full items-center justify-center rounded-full bg-muted text-sm font-medium', cls)}>
  {@render children?.()}
</span>

// packages/ui-angular/src/lib/avatar/avatar-fallback.component.ts
import { Component, Input, HostBinding, ChangeDetectionStrategy } from '@angular/core'
import { cn } from '../../lib/utils'

/** Fallback initials or icon shown when AvatarImage cannot load. */
@Component({
  selector: 'paul-avatar-fallback',
  standalone: true,
  template: `<ng-content />`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AvatarFallbackComponent {
  @Input() class = ''
  @HostBinding('class') get hostClass() {
    return cn('flex h-full w-full items-center justify-center rounded-full bg-muted text-sm font-medium', this.class)
  }
}
