// packages/ui-svelte/src/lib/components/AvatarImage.svelte
<script lang="ts">
  /** Image inside an Avatar. Shows the fallback if the image fails to load. */
  import { cn } from '../utils'
  interface Props { src: string; alt: string; class?: string }
  const { src, alt, class: cls = '' }: Props = $props()
  let error = $state(false)
</script>
{#if !error}
  <img {src} {alt} class={cn('aspect-square h-full w-full', cls)} onerror={() => (error = true)} />
{/if}

// packages/ui-angular/src/lib/avatar/avatar-image.component.ts
import { Component, Input, ChangeDetectionStrategy } from '@angular/core'
import { CommonModule } from '@angular/common'
import { cn } from '../../lib/utils'

/** Image element inside an Avatar. Shows the fallback if the image fails to load. */
@Component({
  selector: 'paul-avatar-image',
  standalone: true,
  imports: [CommonModule],
  template: `
    <img
      *ngIf="!error"
      [src]="src"
      [alt]="alt"
      [class]="imgClass"
      (error)="error = true"
    />
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AvatarImageComponent {
  @Input() src = ''
  @Input() alt = ''
  @Input() class = ''
  error = false
  get imgClass() { return cn('aspect-square h-full w-full', this.class) }
}
