// packages/ui-vue/src/components/card-title.vue
<script setup lang="ts">
import { cn } from '@/lib/utils'
/** Primary heading inside CardHeader. */
defineOptions({ name: 'CardTitle' })
const props = defineProps<{ class?: string }>()
</script>
<template><div :class="cn('font-semibold leading-none tracking-tight', props.class)"><slot /></div></template>

// packages/ui-angular/src/lib/card/card-title.component.ts
import { Component, Input, HostBinding, ChangeDetectionStrategy } from '@angular/core'
import { cn } from '../../lib/utils'

/** Primary heading inside CardHeader. */
@Component({ selector: 'paul-card-title', standalone: true, template: `<ng-content />`, changeDetection: ChangeDetectionStrategy.OnPush })
export class CardTitleComponent {
  @Input() class = ''
  @HostBinding('class') get hostClass() { return cn('font-semibold leading-none tracking-tight', this.class) }
}
