// packages/ui-vue/src/components/card-description.vue
<script setup lang="ts">
import { cn } from '@/lib/utils'
/** Secondary supporting text inside CardHeader. */
defineOptions({ name: 'CardDescription' })
const props = defineProps<{ class?: string }>()
</script>
<template><div :class="cn('text-sm text-muted-foreground', props.class)"><slot /></div></template>

// packages/ui-angular/src/lib/card/card-description.component.ts
import { Component, Input, HostBinding, ChangeDetectionStrategy } from '@angular/core'
import { cn } from '../../lib/utils'

/** Secondary supporting text inside CardHeader. */
@Component({ selector: 'paul-card-description', standalone: true, template: `<ng-content />`, changeDetection: ChangeDetectionStrategy.OnPush })
export class CardDescriptionComponent {
  @Input() class = ''
  @HostBinding('class') get hostClass() { return cn('text-sm text-muted-foreground', this.class) }
}
