// packages/ui-react/src/components/breadcrumb.tsx
import * as React from 'react'
import { Slot } from '@radix-ui/react-slot'
import { ChevronRight, MoreHorizontal } from 'lucide-react'
import { cn } from '@/lib/utils'

/**
 * Root breadcrumb `<nav>` element with `aria-label="breadcrumb"`.
 * @prop separator - Custom separator node overriding the default chevron.
 */
const Breadcrumb = React.forwardRef<
  HTMLElement,
  React.ComponentPropsWithoutRef<'nav'> & {
    separator?: React.ReactNode
  }
>(({ ...props }, ref) => <nav ref={ref} aria-label="breadcrumb" {...props} />)
Breadcrumb.displayName = 'Breadcrumb'

/** Ordered list (`<ol>`) wrapping `BreadcrumbItem` elements. */
const BreadcrumbList = React.forwardRef<
  HTMLOListElement,
  React.ComponentPropsWithoutRef<'ol'>
>(({ className, ...props }, ref) => (
  <ol
    ref={ref}
    className={cn(
      'flex flex-wrap items-center gap-1.5 break-words text-sm text-muted-foreground sm:gap-2.5',
      className
    )}
    {...props}
  />
))
BreadcrumbList.displayName = 'BreadcrumbList'

/** List item (`<li>`) wrapping a single breadcrumb link or page. */
const BreadcrumbItem = React.forwardRef<
  HTMLLIElement,
  React.ComponentPropsWithoutRef<'li'>
>(({ className, ...props }, ref) => (
  <li
    ref={ref}
    className={cn('inline-flex items-center gap-1.5', className)}
    {...props}
  />
))
BreadcrumbItem.displayName = 'BreadcrumbItem'

/**
 * Anchor link inside a breadcrumb item.
 * @prop asChild - When true, merges props onto the child element via Radix Slot.
 */
const BreadcrumbLink = React.forwardRef<
  HTMLAnchorElement,
  React.ComponentPropsWithoutRef<'a'> & {
    asChild?: boolean
  }
>(({ asChild, className, ...props }, ref) => {
  const Comp = asChild ? Slot : 'a'

  return (
    <Comp
      ref={ref}
      className={cn('transition-colors hover:text-foreground', className)}
      {...props}
    />
  )
})
BreadcrumbLink.displayName = 'BreadcrumbLink'

/** Non-interactive span representing the current page. Sets `aria-current="page"`. */
const BreadcrumbPage = React.forwardRef<
  HTMLSpanElement,
  React.ComponentPropsWithoutRef<'span'>
>(({ className, ...props }, ref) => (
  <span
    ref={ref}
    role="link"
    aria-disabled="true"
    aria-current="page"
    className={cn('font-normal text-foreground', className)}
    {...props}
  />
))
BreadcrumbPage.displayName = 'BreadcrumbPage'

/** Decorative separator rendered between breadcrumb items. Hidden from screen readers. */
const BreadcrumbSeparator = ({
  children,
  className,
  ...props
}: React.ComponentProps<'li'>) => (
  <li
    role="presentation"
    aria-hidden="true"
    className={cn('[&>svg]:size-3.5', className)}
    {...props}
  >
    {children ?? <ChevronRight />}
  </li>
)
BreadcrumbSeparator.displayName = 'BreadcrumbSeparator'

/** Ellipsis indicator for collapsed breadcrumb items. Hidden from screen readers. */
const BreadcrumbEllipsis = ({
  className,
  ...props
}: React.ComponentProps<'span'>) => (
  <span
    role="presentation"
    aria-hidden="true"
    className={cn('flex h-9 w-9 items-center justify-center', className)}
    {...props}
  >
    <MoreHorizontal className="h-4 w-4" />
    <span className="sr-only">More</span>
  </span>
)
BreadcrumbEllipsis.displayName = 'BreadcrumbElipssis'

export {
  Breadcrumb,
  BreadcrumbList,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbPage,
  BreadcrumbSeparator,
  BreadcrumbEllipsis,
}

// packages/ui-angular/src/lib/breadcrumb/breadcrumb.component.ts
import { Component, ChangeDetectionStrategy, HostBinding } from '@angular/core'
import { CommonModule } from '@angular/common'
import { cn } from '../../lib/utils'

@Component({ selector: 'paul-breadcrumb', standalone: true, imports: [CommonModule], template: `<nav aria-label="breadcrumb"><ng-content /></nav>`, changeDetection: ChangeDetectionStrategy.OnPush })
export class BreadcrumbComponent {}

@Component({ selector: 'paul-breadcrumb-list', standalone: true, template: `<ol class="flex flex-wrap items-center gap-1.5 break-words text-sm text-muted-foreground sm:gap-2.5"><ng-content /></ol>`, changeDetection: ChangeDetectionStrategy.OnPush })
export class BreadcrumbListComponent {}

@Component({ selector: 'paul-breadcrumb-item', standalone: true, template: `<li class="inline-flex items-center gap-1.5"><ng-content /></li>`, changeDetection: ChangeDetectionStrategy.OnPush })
export class BreadcrumbItemComponent {}

@Component({ selector: 'paul-breadcrumb-link', standalone: true, template: `<a class="transition-colors hover:text-foreground"><ng-content /></a>`, changeDetection: ChangeDetectionStrategy.OnPush })
export class BreadcrumbLinkComponent {}

@Component({ selector: 'paul-breadcrumb-page', standalone: true, template: `<span role="link" aria-disabled="true" aria-current="page" class="font-normal text-foreground"><ng-content /></span>`, changeDetection: ChangeDetectionStrategy.OnPush })
export class BreadcrumbPageComponent {}

@Component({ selector: 'paul-breadcrumb-separator', standalone: true, template: `<li role="presentation" aria-hidden="true" class="[&>svg]:w-3.5 [&>svg]:h-3.5"><ng-content></ng-content></li>`, changeDetection: ChangeDetectionStrategy.OnPush })
export class BreadcrumbSeparatorComponent {}
